<?php

namespace App\Http\Livewire\Modulos;

use App\Http\Livewire\Layouts\Modal;
use App\Models\Modulo;

class Save extends Modal
{
    public Modulo $modulo;
    // Propiedades del formulario
    public $nombre;
    public $descripcion;
    public $icono = 'bi-box-seam'; // Ícono por defecto (Bootstrap Icons)
    public $icono_color = '#4f46e5'; // Color por defecto
    public $cant_funciones = 1;
    public $costo_base = 0.00;

    public function mount()
    {
        if (isset($this->modulo)) {
            $this->nombre = $this->modulo->nombre;
            $this->descripcion = $this->modulo->descripcion;
            $this->icono = $this->modulo->icono;
            $this->icono_color = $this->modulo->icono_color;
            $this->cant_funciones = $this->modulo->cant_funciones;
            $this->costo_base = $this->modulo->costo_base;
        } else {
            $this->modulo = new Modulo();
        }
    }

    // Reglas de validación
    protected $rules = [
        'nombre' => 'required|string|min:3|max:100',
        'descripcion' => 'nullable|string|max:500',
        'icono' => 'required|string',
        'icono_color' => 'required|string|regex:/^#[a-fA-F0-9]{6}$/', // Hexadecimal válido
        'cant_funciones' => 'required|integer|min:1',
        'costo_base' => 'required|numeric|min:0',
    ];

    // Mensajes de error personalizados
    // protected $messages = [
    //     'nombre.required' => 'Campo obligatorio.',
    //     'icono_color.regex' => 'El formato del color debe ser un Hexadecimal válido.',
    //     'cant_funciones.min' => 'El módulo debe tener al menos 1 función.',
    //     'costo_base.min' => 'El costo base no puede ser negativo.',
    // ];
    public static function modalMaxWidthClass(): string
    {
        return 'modal-xl'; // TODO: Change the autogenerated stub
    }

    public function render()
    {
        return view('livewire.modulos.save');
    }

    public function save()
    {
        $validatedData = $this->validate();

        // Persistencia en la Base de Datos
        $this->modulo->fill($validatedData)->save();

        // Emitir alerta de éxito (puedes atraparla con SweetAlert o Bootstrap Toasts)

        $this->emit('show-toast', __('site.modules.save.module_saved'), 'success');

        $this->emit('$refresh');
        $this->emit('closeModal');
    }

    public function init()
    {
        if (user()->cannot($this->modulo->id ? 'update' : 'create', $this->modulo->id ? $this->modulo : [Modulo::class])) {
            $this->emit('show-toast', __('site.common.client_no_permissions'), 'danger');
            $this->emit('closeModal');
            return;
        }
    }
}
