<?php

namespace App\Http\Livewire\Facturas;

use App\Http\Livewire\Layouts\Modal;
use App\Models\MotivoCancelacionFactura;
use App\Models\Facturador;
use App\Models\Factura;

class Timbrar extends Modal
{
    public $scope;
    public Factura $factura;
    public string $type;
    public $folio;
    protected $listeners = ['$refresh'];

    public function mount()
    {
        $this->type = 'Factura';
        $this->folio = $this->factura->serie->descripcion . '-' . Factura::internalSheetGenerator($this->factura->serie_id, modo_facturacion() == 1);
    }

    public static function modalMaxWidthClass(): string
    {
        return 'modal-lg'; // TODO: Change the autogenerated stub
    }

    public function getModoProperty()
    {
        return system_config('cfdi_timbrado_productivo') ? 'PRODUCCION' : 'PRUEBA';
    }

    public function getTextAlertProperty()
    {
        return 'La Factura con folio <b>' . $this->folio . '</b> será timbrada';
    }

    public function render()
    {
        return view('livewire.facturas.timbrar');
    }

    public function timbrar()
    {
        $facturador = new Facturador($this->factura->propietario);
        $res = $facturador->timbrarFactura($this->factura->id, $this->folio);
        // $this->date = now()->format('Y-m-d H:i:s');
        $this->emit('show-toast', $res['message'], $res['success'] ? 'success' : 'danger');

        if ($res['success']) {
            $this->emit('$refresh');
            $this->emit('closeModal');
        }
    }
}
