<?php

namespace App\Http\Livewire\Cuarentena;

use App\Actions\ProcesarTicketCuarentena;
use App\Http\Livewire\Layouts\Modal;
use App\Models\Cliente;
use App\Models\Cuarentena;
use App\Models\Sucursal;
use App\Models\Terminal;
use Illuminate\Support\Facades\Crypt;

class Fix extends Modal
{
    public Cuarentena $registro;

    public array $formData = [];
    public array $items = [];

    public $ip;
    public $cliente_id;
    public $sucursal_id;
    public $terminal_id;

    public bool $modoAvanzado = false;
    public string $rawJson = '';

    public $clientesDisponibles = [];
    public $sucursalesDisponibles = [];
    public $terminalesDisponibles = [];
    public $confirmDescartarRegistroClass = '';

    public function mount()
    {
        $this->ip = $this->registro->ip;
        $this->cliente_id = $this->registro->cliente_id;
        $this->sucursal_id = $this->registro->sucursal_id;
        $this->terminal_id = $this->registro->terminal_id;

        $this->clientesDisponibles = Cliente::where('es_cliente', 1)->orderBy('id')->lazy()->map(function ($value) {
            return [
                'value' => $value->id,
                'label' => Crypt::decrypt($value->nombre_comercial)
            ];
        })->toArray();

        if ($this->cliente_id) {
            $this->cargarSucursales();
        }
        if ($this->sucursal_id) {
            $this->cargarTerminales();
        }

        $decoded = json_decode($this->registro->data, true);

        // Si el JSON venía corrupto/no parseable, arrancamos con estructura vacía
        // para que el usuario pueda reconstruirlo desde el formulario.
        if (json_last_error() !== JSON_ERROR_NONE || !is_array($decoded)) {
            $decoded = $this->estructuraVacia();
            // Forzamos modo avanzado porque no hay nada coherente que mostrar en el formulario
            $this->modoAvanzado = true;
        }

        $this->items = $decoded['Items'] ?? [];
        unset($decoded['Items']);
        $this->formData = $decoded;

        $this->rawJson = $this->registro->data;
    }

    public static function modalMaxWidthClass(): string
    {
        return 'modal-xl'; // TODO: Change the autogenerated stub
    }
    public function hydrate()
    {
        $this->dispatchBrowserEvent('reApplySelect2');
    }
    public function updated()
    {
        $this->dispatchBrowserEvent('reApplySelect2');
    }

    protected function estructuraVacia(): array
    {
        return [
            'Items' => [],
            'PosId' => '',
            'ClerkId' => '',
            'ClerkName' => '',
            'APIPassword' => '',
            'APIUserName' => '',
            'FiscalInvoice' => 'No',
            'PrinterHeader' => null,
            'TransactionId' => '',
            'CustomerFiscalId' => '',
            'MerchantFiscalId' => '',
            'TransactionEndTime' => '',
            'TransactionStartTime' => '',
        ];
    }

    public function updatedClienteId($value)
    {
        $this->sucursal_id = null;
        $this->terminal_id = null;
        $this->terminalesDisponibles = [];
        $this->cargarSucursales();
    }

    public function updatedSucursalId($value)
    {
        $this->terminal_id = null;
        $this->cargarTerminales();
    }
    public function updatedTerminalId($value)
    {
        if ($value) {
            $this->modoAvanzado = false;
            if (isset($this->formData['TerminalId']))
                $this->formData['TerminalId'] = Terminal::find($value)->identificador;
            elseif (isset($this->formData['MerchantFiscalId']))
                $this->formData['MerchantFiscalId'] = Terminal::find($value)->identificador;
            elseif (isset($this->formData['APIUserName']))
                $this->formData['APIUserName'] = Terminal::find($value)->identificador;
        }
    }

    protected function cargarSucursales()
    {
        $this->sucursalesDisponibles = $this->cliente_id
            ? Sucursal::where('cliente_id', $this->cliente_id)->orderBy('nombre_comercial')->lazy()->map(function ($value) {
                return [
                    'value' => $value->id,
                    'label' => Crypt::decrypt($value->nombre_comercial)
                ];
            })->toArray()
            : [];
    }

    protected function cargarTerminales()
    {
        $this->terminalesDisponibles = $this->sucursal_id
            ? Terminal::where('sucursal_id', $this->sucursal_id)->orderBy('nombre')->lazy()->map(function ($value) {
                return [
                    'value' => $value->id,
                    'label' => $value->nombre ? ("$value->nombre - $value->identificador") : $value->identificador
                ];
            })->toArray()
            : [];
    }

    public function agregarItem()
    {
        $this->items[] = [
            'Id' => '',
            'Qty' => '1',
            'SKU' => '',
            'Tip' => '0',
            'Name' => '',
            'Type' => 'Product',
            'Amount' => '0',
            'Taxable' => '0',
            'Discount' => '0',
            'Surcharge' => '0',
            'PriceLevel' => '1',
            'MerchantFee' => '0',
            'DepartmentId' => '0',
            'DepartmentName' => '',
            'ExemptedTaxAmount' => '0',
        ];
    }

    public function eliminarItem($index)
    {
        unset($this->items[$index]);
        $this->items = array_values($this->items);
    }

    public function toggleModoAvanzado()
    {
        if ($this->modoAvanzado) {
            // Venimos DE avanzado HACIA formulario: intentamos parsear lo escrito en rawJson
            $this->sincronizarDesdeRaw();
        } else {
            // Venimos DE formulario HACIA avanzado: regeneramos el raw desde los campos actuales
            $this->rawJson = $this->jsonReconstruido(true);
        }
    }

    protected function sincronizarDesdeRaw()
    {
        $decoded = json_decode($this->rawJson, true);

        if (json_last_error() !== JSON_ERROR_NONE) {
            $this->addError('rawJson', 'El JSON no es válido: ' . json_last_error_msg());
            // Revertimos el toggle para que no pierda su trabajo en modo avanzado
            $this->modoAvanzado = true;
            return;
        }

        $this->items = $decoded['Items'] ?? [];
        unset($decoded['Items']);
        $this->formData = $decoded;
    }

    public function formatearJson()
    {
        $decoded = json_decode($this->rawJson, true);

        if (json_last_error() !== JSON_ERROR_NONE) {
            $this->addError('rawJson', 'No se puede formatear: el JSON no es válido.');
            return;
        }

        $this->rawJson = json_encode($decoded, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    }

    protected function jsonReconstruido(bool $prettyPrint = false): string
    {
        $data = $this->formData;
        $data['Items'] = $this->items;

        $flags = JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES;
        if ($prettyPrint) {
            $flags |= JSON_PRETTY_PRINT;
        }

        return json_encode($data, $flags);
    }

    // Computed property para el preview en el sidebar
    public function getPreviewJsonProperty(): string
    {
        if ($this->modoAvanzado) {
            $decoded = json_decode($this->rawJson, true);
            if (json_last_error() !== JSON_ERROR_NONE) {
                return '// JSON inválido, no se puede previsualizar';
            }
            return json_encode($decoded, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        }

        return $this->jsonReconstruido(true);
    }

    protected function rules()
    {
        $rules = [
            'ip' => 'nullable|ip',
            'cliente_id' => 'nullable|exists:tb_clientes,id',
            'sucursal_id' => 'nullable|exists:tb_sucursales,id',
            'terminal_id' => 'nullable|exists:tb_terminales,id',
        ];

        if ($this->modoAvanzado) {
            $rules['rawJson'] = 'required|string';
        } else {
            $rules['formData.PosId'] = 'required|string';
            $rules['formData.TransactionId'] = 'required|string';
            $rules['formData.TransactionStartTime'] = 'nullable|date_format:d/m/Y H:i:s';
            $rules['formData.TransactionEndTime'] = 'nullable|date_format:d/m/Y H:i:s';
            $rules['items'] = 'array|min:1';
        }

        return $rules;
    }

    protected function jsonFinal(): ?string
    {
        if ($this->modoAvanzado) {
            $decoded = json_decode($this->rawJson, true);
            if (json_last_error() !== JSON_ERROR_NONE) {
                $this->addError('rawJson', 'El JSON no es válido: ' . json_last_error_msg());
                return null;
            }
            return json_encode($decoded, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        }

        return $this->jsonReconstruido();
    }

    public function guardar()
    {
        $this->validate();

        $json = $this->jsonFinal();
        if ($json === null) {
            return; // ya se agregó el error de validación
        }

        $this->registro->update([
            'ip' => $this->ip,
            'data' => $json,
            'cliente_id' => $this->cliente_id,
            'sucursal_id' => $this->sucursal_id,
            'terminal_id' => $this->terminal_id,
        ]);

        $this->emit('show-toast', 'Registro guardo correctamente', 'success');
        $this->emit('$refresh');
        $this->emit('closeModal');
    }

    public function guardarYReprocesar()
    {
        $this->validate();

        $json = $this->jsonFinal();
        if ($json === null) {
            return;
        }

        $this->registro->update([
            'ip' => $this->ip,
            'data' => $json,
            'cliente_id' => $this->cliente_id,
            'sucursal_id' => $this->sucursal_id,
            'terminal_id' => $this->terminal_id,
        ]);

        try {
            // TODO: reemplazar por la llamada real a tu servicio/job de procesamiento de tickets
            // Ejemplo: app(ProcesadorTicketsService::class)->procesar($this->registro);
            $procesador = new ProcesarTicketCuarentena($this->registro);
            $res = $procesador->execute();

            if ($res) {
                $this->registro->delete(); // o marcar como resuelto, según tu flujo
                $this->emit('show-toast', 'Registro procesado correctamente.', 'success');
                $this->emit('$refresh');
                $this->emit('closeModal');
            } else {
                $this->emit('show-toast', 'El registro aun presenta problemas. Porfavor revisar nuevamente.', 'danger');
                $this->emit('$refresh');
            }
        } catch (\Throwable $e) {
            $this->addError('rawJson', 'El JSON se guardó pero el reproceso falló: ' . $e->getMessage());
        }
    }

    public function descartar()
    {
        $this->registro->delete();
        $this->emit('show-toast', 'Registro eliminado correctamente', 'success');
        $this->emit('$refresh');
        $this->emit('closeModal');
    }

    public function showDescartarRegistroModal()
    {
        $this->confirmDescartarRegistroClass = 'show';
    }

    public function render()
    {
        return view('livewire.cuarentena.fix');
    }

    public function init()
    {
        if (user()->cannot('fix', $this->registro)) {
            $this->emit('show-toast', 'No tiene permisos para realizar estar acción.', 'danger');
            $this->emit('closeModal');
            return;
        }
    }
}
