<?php

namespace App\Livewire\Terminales;

use App\Livewire\Layouts\Modal;
use App\Models\Sucursal;
use App\Models\Suscripcion;
use App\Models\Terminal;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class SaveSystem extends Modal
{
    public $scope = null;

    public Terminal $terminal;
    public $nombre;
    public $identificador;
    public $es_vk;
    public $comentarios;
    public $sucursal_id;
    public $cliente_id;
    public $suscripcion_id;

    public $sucursales = [];
    public $suscripciones = [];
    public $clientes = [];
    public $from_subscription = false;
    public $sucursalesFromSubsOpts;
    protected $listeners = ['$refresh'];

    public function mount()
    {
        $this->nombre = isset($this->terminal) ? $this->terminal->nombre : '';
        $this->identificador = isset($this->terminal) ? $this->terminal->identificador : str_shuffle(uniqid());
        $this->comentarios = isset($this->terminal) ? $this->terminal->comentarios : '';
        $this->es_vk = isset($this->terminal) ? $this->terminal->es_vk : false;
        $this->suscripcion_id = isset($this->terminal) ? $this->terminal->suscripcion_id : '';
        if (!$this->sucursal_id)
            $this->sucursal_id = isset($this->terminal) ? $this->terminal->sucursal_id : '';
        if ($this->sucursal_id)
            $this->cliente_id = Sucursal::find($this->sucursal_id)->cliente_id;

        if (!isset($this->terminal)) {
            $this->terminal = new Terminal();
        }

        $this->clientes = DB::table('tb_clientes')
            ->select('id as value', 'nombre_comercial as label')
            ->where('es_cliente', 1)
            ->where('deleted_at', null)
            ->get()->map(function ($element) {
                $element->label = Crypt::decrypt($element->label);
                return (array) $element;
            })->toArray();

        if ($this->cliente_id) {
            $sucursales_q = DB::table('tb_sucursales')
                ->select('id as value', 'nombre_comercial as label')
                ->where('deleted_at', null)
                ->where('cliente_id', $this->cliente_id);

            if ($this->from_subscription)
                $sucursales_q->whereIn('id', explode(',', $this->sucursalesFromSubsOpts));
            
            $this->sucursales = $sucursales_q->get()->map(function ($element) {
                $element->label = Crypt::decrypt($element->label);
                return (array) $element;
            })->toArray();
            $this->loadSuscripciones();
        }
    }

    public function hydrate()
    {
        $this->dispatch('reApplySelect2');
    }

    public static function modalMaxWidthClass(): string
    {
        return 'modal-lg'; // TODO: Change the autogenerated stub
    }

    public function updatedClienteId($value)
    {
        $this->sucursal_id = null;
        $this->sucursales = [];
        $this->suscripcion_id = null;
        $this->suscripciones = [];
        if ($value) {
            $this->sucursales = DB::table('tb_sucursales')
                ->select('id as value', 'nombre_comercial as label')
                ->where('deleted_at', null)
                ->where('cliente_id', $value)
                ->get()->map(function ($element) {
                    $element->label = Crypt::decrypt($element->label);
                    return (array) $element;
                })->toArray();

            $this->loadSuscripciones();
        }
    }

    public function getWithScopeProperty()
    {
        return $this->scope != null;
    }

    public function render()
    {
        return view('livewire.terminales.save-system');
    }

    public function init()
    {
        if (user()->cannot($this->terminal->exists() ? 'update' : 'create', $this->terminal->exists() ? $this->terminal : [Terminal::class])) {
            $this->dispatch('show-toast', __('site.common.client_no_permissions'), 'danger');
            $this->dispatch('closeModal');
            return;
        }
    }

    public function save()
    {
        $rules = $this->terminal->rules();
        $messages = $this->terminal->messages();
        $data = $this->validate(
            $rules,
            // $messages
        );

        if (!$this->terminal->exists())
            while (DB::table(table: 'tb_terminales')->where('identificador', $data['identificador'])->count() > 0) {
                $data['identificador'] = str_shuffle(uniqid());
            }

        $this->terminal->fill($data)->save();

        if ($this->terminal->isDirty('sucursal_id') && $this->terminal->suscripcion_id) {
            if (
                !$this->terminal->sucursal->suscripcion ||
                $this->terminal->suscripcion_id != $this->terminal->sucursal->suscripcion_id
            ) {
                if (!$this->terminal->sucursal->suscripcion) {
                    $this->terminal->suscripcion_id = null;
                    $this->terminal->save();
                } else {
                    if ($this->terminal->sucursal->suscripcion->terminales->count() < $this->terminal->sucursal->suscripcion->cant_terminales) {
                        $this->terminal->suscripcion_id = $this->terminal->sucursal->suscripcion_id;
                        $this->terminal->save();
                    }
                }
            }
        }

        $attributes = Arr::except($this->terminal->getDirty(), ['created_at', 'updated_at', 'deleted_at']);
        if ($this->terminal->wasRecentlyCreated) {
            $log = __('site.terminals.save.log_created_detail', ['name' => $this->terminal->nombre]);
            activity(__('site.terminals.save.log_created'))
                ->on($this->terminal)
                ->event('created')
                ->withProperties(Terminal::parseData($attributes))
                ->log($log);
        } else {
            $log = __('site.terminals.save.log_updated_detail', ['name' => $this->terminal->nombre]);
            activity(__('site.terminals.save.log_updated'))
                ->on($this->terminal)
                ->event('updated')
                ->withProperty('attributes', Terminal::parseData($attributes))
                ->withProperty('old', Terminal::parseData(Arr::only($this->terminal->getOriginal(), array_keys($attributes))))
                ->log($log);
        }

        $this->dispatch('show-toast', __('site.terminals.save.terminal_saved'));

        if ($this->scope) {
            if ($this->terminal->wasRecentlyCreated) {
                $this->dispatch('terminal-created', $this->terminal->id)->to($this->scope);
            } else {
                $this->dispatch('terminal-updated', $this->terminal->id)->to($this->scope);
            }
        } else {
            $this->dispatch('$refresh');
        }
        $this->dispatch('closeModal');
    }

    public function loadSuscripciones()
    {
        Suscripcion::where('estado', 'ACTIVA')->where('cliente_id', $this->cliente_id)->withCount('terminales')->each(function (Suscripcion $suscripcion) {
            if (
                $suscripcion->terminales_count < $suscripcion->cant_terminales
                || $suscripcion->id == $this->suscripcion_id
            ) {
                $this->suscripciones[] = $suscripcion->only(['value', 'label']);
            }
        });
    }
}
