<?php

namespace App\Livewire\Terminales;

use App\Livewire\Layouts\Modal;
use App\Models\Sucursal;
use App\Models\Suscripcion;
use App\Models\Terminal;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class Save extends Modal
{
    public $scope = null;

    public Terminal $terminal;
    public $nombre;
    public $identificador;
    public $es_vk;
    public $comentarios;
    public $sucursal_id;
    public $cliente_id;
    public $suscripcion_id;
    protected $listeners = ['$refresh'];

    public function mount()
    {
        $this->nombre = isset($this->terminal) ? $this->terminal->nombre : '';
        $this->identificador = isset($this->terminal) ? $this->terminal->identificador : str_shuffle(uniqid());
        $this->es_vk = isset($this->terminal) ? $this->terminal->es_vk : false;
        $this->comentarios = isset($this->terminal) ? $this->terminal->comentarios : '';
        if (!isset($this->terminal)) {
            $this->terminal = new Terminal();
        }
    }

    public function hydrate()
    {
        $this->dispatch('reApplySelect2');
    }

    public static function modalMaxWidthClass(): string
    {
        return 'modal-lg'; // TODO: Change the autogenerated stub
    }
    public function render()
    {
        return view('livewire.terminales.save');
    }

    public function init()
    {
        if (user()->cannot($this->terminal->exists() ? 'update' : 'create', $this->terminal->exists() ? $this->terminal : [Terminal::class])) {
            $this->dispatch('show-toast', __('site.common.client_no_permissions'), 'danger');
            $this->dispatch('closeModal');
            return;
        }
    }

    public function save()
    {
        $data = $this->validate(
            [
                'nombre' => ['required'],
                'identificador' => ['required'],
                'es_vk' => ['nullable', 'boolean'],
                'comentarios' => ['nullable'],
            ],
            // $messages
        );

        $this->terminal->fill($data)->save();

        $attributes = Arr::except($this->terminal->getDirty(), ['created_at', 'updated_at', 'deleted_at']);
        if ($this->terminal->wasRecentlyCreated) {
            $log = __('site.terminals.save.log_created_detail', ['name' => $this->terminal->nombre]);
            activity(__('site.terminals.save.log_created'))
                ->on($this->terminal)
                ->event('created')
                ->withProperties(Terminal::parseData($attributes))
                ->log($log);
        } else {
            $log = __('site.terminals.save.log_updated_detail', ['name' => $this->terminal->nombre]);
            activity(__('site.terminals.save.log_updated'))
                ->on($this->terminal)
                ->event('updated')
                ->withProperty('attributes', Terminal::parseData($attributes))
                ->withProperty('old', Terminal::parseData(Arr::only($this->terminal->getOriginal(), array_keys($attributes))))
                ->log($log);
        }

        $this->dispatch('show-toast', __('site.terminals.save.terminal_saved'));
        $this->dispatch('$refresh');
        $this->dispatch('closeModal');
    }
}
