<?php

namespace App\Http\Livewire\Paquetes;

use App\Http\Livewire\Layouts\Modal;
use App\Models\Config;
use App\Models\Modulo;
use App\Models\Paquete;
use Illuminate\Support\Arr;

class Save extends Modal
{
    public Paquete $paquete;
    // Propiedades del formulario
    public $nombre;
    public $descripcion;
    public $precio = 0.00;
    public $cant_sucursales;
    public $cant_terminales;
    public $cant_usuarios;
    public $cant_timbres;
    public $cant_meses_analitica_basica;
    public $modulos = [];

    public $globalSettings = [];

    public function mount()
    {
        if (isset($this->paquete)) {
            $this->nombre = $this->paquete->nombre;
            $this->descripcion = $this->paquete->descripcion;
            $this->precio = $this->paquete->precio;
            $this->cant_sucursales = $this->paquete->cant_sucursales;
            $this->cant_terminales = $this->paquete->cant_terminales;
            $this->cant_usuarios = $this->paquete->cant_usuarios;
            $this->cant_timbres = $this->paquete->cant_timbres;
            $this->cant_meses_analitica_basica = $this->paquete->cant_meses_analitica_basica;
            $this->modulos = $this->paquete->modulos()->pluck('id')->toArray();
        } else {
            $this->paquete = new Paquete();
            $this->modulos = Modulo::whereIn('id', [1, 2])->pluck('id')->toArray();
        }

        $this->globalSettings = Config::all()->pluck('valor', 'llave')->toArray();
    }

    // Reglas de validación
    protected function rules()
    {
        return [
            'nombre' => 'required|string|min:3|max:100',
            'descripcion' => 'nullable|string|max:500',
            'precio' => 'required|numeric|min:0',
            'cant_sucursales' => 'required|numeric|min:1',
            'cant_terminales' => 'required|numeric|min:1',
            'cant_usuarios' => 'required|numeric|min:1',
            // Valida que sea un array, obligatorio y que tenga como mínimo 2 elementos seleccionados
            'modulos' => 'required|array|min:2',
            'modulos.*' => 'exists:tb_modulos,id', // Opcional: valida que los IDs existan en la BD
        ];
    }

    // Mensajes personalizados para la regla del mínimo de módulos
    // protected $messages = [
    //     'nombre.required' => 'Campo obligatorio.',
    //     'precio.required' => 'Campo obligatorio.',
    //     'precio.min' => 'El precio no puede ser un valor negativo.',
    //     'cant_sucursales.required' => 'Campo obligatorio.',
    //     'cant_sucursales.min' => 'Se debe permitir al menos una sucursal.',
    //     'cant_terminales.required' => 'Campo obligatorio.',
    //     'cant_terminales.min' => 'Se debe permitir al menos una terminal.',
    //     'cant_usuarios.required' => 'Campo obligatorio.',
    //     'cant_usuarios.min' => 'Se debe permitir al menos un usuario.',
    //     'modulos.required' => 'Debes seleccionar los módulos que componen este paquete.',
    //     'modulos.min' => 'Un paquete debe estar conformado por al menos 2 módulos.',
    // ];
    public static function modalMaxWidthClass(): string
    {
        return 'modal-xl'; // TODO: Change the autogenerated stub
    }

    public function getBillingIncludedProperty()
    {
        return in_array(3, $this->modulos);
    }
    public function getBasicAnalyticIncludedProperty()
    {
        return in_array(4, $this->modulos);
    }

    public function render()
    {
        $availableModules = Modulo::all();
        return view('livewire.paquetes.save', [
            'availableModules' => $availableModules
        ]);
    }

    public function save()
    {
        $rules = $this->rules();
        if ($this->billing_included)
            $rules = array_merge($rules, ['cant_timbres' => 'required|numeric|min:1']);
        if ($this->basic_analytic_included)
            $rules = array_merge($rules, ['cant_meses_analitica_basica' => 'required|numeric|min:1']);

        $validatedData = $this->validate($rules);

        if ($this->paquete->id) {
            $this->paquete->modulos()->sync($validatedData['modulos']);

            $suscripciones = $this->paquete->suscripciones()->with('modulos')->get();
            foreach ($validatedData['modulos'] as $mod) {
                foreach ($suscripciones as $sub) {
                    if ($sub->modulos->where('id', $mod)->count() == 0) {
                        $sub->modulos()->syncWithoutDetaching($mod);
                    }
                }
            }
        }

        // Persistencia en la Base de Datos
        $this->paquete->fill(Arr::except($validatedData, ['modulos']))->save();
        // $this->paquete->fill(Arr::except($validatedData, ['modulos']))->save();
        if ($this->paquete->wasRecentlyCreated)
            $this->paquete->modulos()->sync($validatedData['modulos']);

        $this->emit('show-toast', __('site.packages.save.package_saved'), 'success');

        $this->emit('$refresh');
        $this->emit('closeModal');
    }

    public function init()
    {
        if (user()->cannot($this->paquete->id ? 'update' : 'create', $this->paquete->exists() ? $this->paquete : [Paquete::class])) {
            $this->emit('show-toast', __('site.common.client_no_permissions'), 'danger');
            $this->emit('closeModal');
            return;
        }
    }
}
