<?php

namespace App\Http\Livewire\FacturasSistema;

use App\Http\Livewire\Layouts\Modal;
use App\Models\Cliente;
use App\Models\MotivoCancelacionFactura;
use App\Models\Factura;
use App\Services\Timbrado\Facturador;

class Cancel extends Modal
{
    public $scope;
    public Factura $factura;
    public string $type;
    public $motivo = null;
    public $factura_sustituta = null;
    public $motivos = [];
    public $facturas = [];

    protected $listeners = ['$refresh'];

    public function mount(Factura $factura, string $scope)
    {
        $this->factura = $factura;
        $this->scope = $scope;

        if ($this->factura->es_complemento)
            $this->type = __('site.common.complement');
        else if ($this->factura->es_nota_credito)
            $this->type = __('site.common.credit_note');
        else
            $this->type = __('site.common.invoice');

        $this->motivos = MotivoCancelacionFactura::all()->map->only(['label', 'value'])->toArray();
        $this->facturas = Factura::where('estado', 'TIMBRADA')->lazy()->map(function (Factura $factura) {
            $factura->cliente = Cliente::decryptInfo($factura->cliente);
            return [
                'value' => $factura->id,
                'label' => $factura->label
            ];
        })->toArray();
    }

    public static function modalMaxWidthClass(): string
    {
        return 'modal-lg'; // TODO: Change the autogenerated stub
    }

    public function updatedMotivo($value)
    {
        $this->factura_sustituta = null;
    }

    public function getMostrarSustitutosProperty()
    {
        return $this->motivo == 1;
    }

    public function getModoProperty()
    {
        return $this->factura->modo_prueba_cfdi ? __('site.common.testing') : __('site.common.production');
    }

    public function getTextAlertProperty()
    {
        return __('site.invoices.cancel.invoice_to_cancel', ['type' => $this->type, 'folio' => $this->factura->folio_interno]);
    }

    public function render()
    {
        return view('livewire.facturas-sistema.cancel');
    }

    public function init()
    {
        if (user()->cannot('cancelFacturaSistema', $this->factura)) {
            $this->emit('show-toast', __('site.common.client_no_permissions'), 'danger');
            $this->emit('closeModal');
            return;
        }
    }

    public function cancel()
    {
        $data = $this->validate(
            [
                'motivo' => ['required', 'exists:tb_motivos_cancelacion_factura,id'],
                'factura_sustituta' => ['required_if:motivo,1'],
            ],
            // [
            //     'motivo.required' => 'Campo requerido!',
            //     'motivo.exists' => 'Motivo no encontrado!',
            //     'factura_sustituta.exists' => 'Factura no encontrada!',
            //     'factura_sustituta.required_if' => 'Campo requerido!'
            // ]
        );

        $facturador = new Facturador($this->factura->propietario);
        $res = $facturador->cancelar($this->factura->id, $data['motivo'], $data['factura_sustituta']);

        $this->emit('show-toast', $res['message'], $res['success'] ? 'success' : 'danger');
        $this->emit('$refresh');
        $this->emit('closeModal');
    }
}
