<?php

namespace App\Http\Livewire\FacturasSistema;

use App\Http\Livewire\Layouts\Modal;
use App\Models\CabeceraFactura;
use App\Models\Cliente;
use App\Models\Factura;
use App\Models\Sucursal;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Crypt;

class PanelPac extends Modal
{
    public $nombre_comercial;
    public $razon_social;
    public $rfc;
    public $cfdi_timbrado_productivo;
    public $portal_pac;
    protected $listeners = ['$refresh', 'changeTimbrado'];

    public static function modalMaxWidthClass(): string
    {
        return 'modal-md'; // TODO: Change the autogenerated stub
    }

    public function mount() {}

    public function updated($field)
    {
        if ($field == 'cfdi_timbrado_productivo')
            $this->changeTimbrado();
    }

    public function render()
    {
        return view('livewire.facturas-sistema.panel-pac');
    }

    public function init()
    {
        if (user()->cannot('setPanelPacFacturaSistema', [Factura::class])) {
            $this->emit('show-toast', 'No tiene permisos para realizar estar acción.', 'danger');
            $this->emit('closeModal');
            return;
        }

        $owner = Cliente::where('es_propietario', 1)->first();
        if (!$owner) {
            $this->emit('show-toast', 'Primero debe guardar la Cabecera de Factura.', 'danger');
            $this->emit('closeModal');
            return;
        }
        $this->nombre_comercial = $owner->nombre_comercial ? Crypt::decrypt($owner->nombre_comercial) : '';
        $this->razon_social = $owner->razon_social ? Crypt::decrypt($owner->razon_social) : '';
        $this->rfc = $owner->rfc;
        $this->portal_pac = $owner->portal_pac;
        $this->cfdi_timbrado_productivo = config('cfdi_timbrado_productivo');
    }

    public function changeTimbrado()
    {
        system_config('cfdi_timbrado_productivo', $this->cfdi_timbrado_productivo);
        $this->emit('show-toast', 'Modo de Timbrado cambiado.');
        $this->emit('$refresh');
    }
}
