<?php

namespace App\Http\Livewire\FacturasSistema;

use App\Http\Livewire\Layouts\Modal;
use App\Models\MotivoCancelacionFactura;
use App\Models\Facturador;
use App\Models\Factura;
use App\Services\Timbrado\Facturador as TimbradoFacturador;

class Timbrar extends Modal
{
    public $scope;
    public Factura $factura;
    public string $type;
    public $folio;
    protected $listeners = ['$refresh'];

    public function mount()
    {
        if ($this->factura->es_complemento)
            $this->type = __('site.common.complement');
        else if ($this->factura->es_nota_credito)
            $this->type = __('site.common.credit_note');
        else
            $this->type = __('site.common.invoice');

        $this->folio = Factura::internalSheetGenerator($this->factura->serie_id, modo_facturacion($this->factura->propietario_id) == 1);
    }

    public static function modalMaxWidthClass(): string
    {
        return 'modal-lg'; // TODO: Change the autogenerated stub
    }

    public function getModoProperty()
    {
        return $this->factura->propietario->cfdi_timbrado_productivo ? __('site.common.production') : __('site.common.testing');
    }

    public function getTextAlertProperty()
    {
        return __('site.invoices.stamp.invoice_to_stamp', ['type' => $this->type, 'folio' => $this->folio]);
    }

    public function render()
    {
        return view('livewire.facturas-sistema.timbrar');
    }

    public function timbrar()
    {
        $facturador = new TimbradoFacturador($this->factura->propietario);
        $res = $facturador->timbrarFactura($this->factura->id, $this->folio);
        // $this->date = now()->format('Y-m-d H:i:s');
        $this->emit('show-toast', $res['message'], $res['success'] ? 'success' : 'danger');

        if ($res['success']) {
            $this->emit('$refresh');
            $this->emit('closeModal');
        }
    }
}
