<?php

namespace App\Livewire\CuentasCobrar;

use App\Livewire\Layouts\Modal;
use App\Models\Factura;

class Show extends Modal
{
    public $scope;
    public Factura $factura;
    public $pagos = [];

    protected $listeners = ['$refresh'];

    public function mount()
    {
        $this->pagos = $this->factura->ingresos()->get()->map(function($element){
            return[
                'fecha_str' => $element->fecha->format('d/m/Y'),
                'monto' => $element->pivot->monto,
                'moneda' => $element->pivot->moneda
            ];
        })->toArray();
    }

    public static function modalMaxWidthClass(): string
    {
        return 'modal-lg'; // TODO: Change the autogenerated stub
    }

    public function getTipoProperty(){
        return __('site.common.invoice');
    }
    public function render()
    {
        return view('livewire.cuentas-cobrar.show');
    }
}
