<?php

namespace App\Http\Livewire\Auth;

use App\Http\Livewire\Layouts\Modal;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Livewire\Component;

class ChangePassword extends Modal
{
    public $current_password;
    public $password;
    public $password_confirmation;

    public function render()
    {
        return view('livewire.auth.change-password');
    }

    public static function modalMaxWidthClass(): string
    {
        return 'modal-md'; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            'current_password' => ['required', 'current_password'],
            'password' => ['required', 'confirmed'],
        ];
    }

    public function messages()
    {
        return [
            'current_password.required' => 'Entre la contraseña actual.',
            'current_password.current_password' => 'La contraseña es incorrecta.',
            'password.required' => 'Entre la nueva contraseña.',
            'password.confirmed' => 'La nueva contraseña no coincide con la actual.',
        ];
    }

    public function update()
    {
        $this->validate($this->rules(), $this->messages());

        user()->update(['password' => Hash::make($this->password)]);

        $this->emit('show-toast', 'Contraseña actualizada.');
        $this->emit('closeModal');
    }
}
