<?php

namespace App\Http\Livewire\Comensales;

use App\Http\Livewire\Layouts\Modal;
use App\Models\RegimenFiscal;
use App\Models\Direccion;
use App\Models\Estado;
use App\Models\Localidad;
use App\Models\Municipio;
use App\Models\Cliente;
use App\Rules\RfcRule;
use App\Rules\RfcYRegimenCoherentesRule;
use App\Rules\RuleUnique;
use Exception;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Livewire\WithFileUploads;
use Smalot\PdfParser\Parser;

class Save extends Modal
{
    use WithFileUploads;
    public $scope = null;
    public Cliente $comensal;
    public $nombre_comercial;
    public $razon_social;
    public $rfc;
    public $correo;
    public $telefono;
    public $comentarios;
    public $con_facturacion;
    public $regimen_fiscal_id;
    public $direccion_fiscal;
    public $constancia_fiscal;

    public $regimenesFiscales = [];
    public $estados = [];

    protected $listeners = ['$refresh'];

    public function mount()
    {
        $this->regimenesFiscales = RegimenFiscal::orderBy('codigo')->get()->map->only(['label', 'value']);

        if (!isset($this->comensal)) {
            $this->comensal = new Cliente();
        } else {
            $this->comensal = Cliente::decryptInfo($this->comensal);
            $this->nombre_comercial = $this->comensal->nombre_comercial;
            $this->razon_social = $this->comensal->razon_social;
            $this->rfc = $this->comensal->rfc;
            $this->correo = $this->comensal->correo;
            $this->telefono = $this->comensal->telefono;
            $this->comentarios = $this->comensal->comentarios;
            $this->con_facturacion = $this->comensal->con_facturacion;
            $this->regimen_fiscal_id = $this->comensal->regimen_fiscal_id;
        }
        $this->direccion_fiscal = $this->comensal->direccion_fiscal->toArray();
        $this->estados = get_estados_mexico();
    }

    public static function modalMaxWidthClass(): string
    {
        return 'modal-xl'; // TODO: Change the autogenerated stub
    }

    public function updatedConstanciaFiscal($value)
    {
        if ($value) {
            if ($value->getMimeType() != 'application/pdf') {
                $this->emit('show-toast', __('site.diners.save.invalid_file_type'), 'danger');
                return;
            }

            try {
                $parser = new Parser();
                $content = file_get_contents($value->getRealPath());
                $pdf = $parser->parseContent($content);
                $text = $pdf->getText();

                $datos_fiscales = extraer_datos_fiscales($text);

                if ($datos_fiscales['tipo_persona'] == 'fisica') {
                    $nombre = $datos_fiscales['nombre'] . ' ' . $datos_fiscales['apellido_paterno'] . ' ' . $datos_fiscales['apellido_materno'];
                    $this->razon_social = $nombre;
                    $this->nombre_comercial = $nombre;
                } else {
                    $this->razon_social = $datos_fiscales['razon_social'];
                    $this->nombre_comercial = $datos_fiscales['nombre_comercial'];
                }
                $this->rfc = $datos_fiscales['rfc'];
                $this->direccion_fiscal['codigo_postal'] = $datos_fiscales['codigo_postal'];
                $this->direccion_fiscal['calle'] = $datos_fiscales['calle'];
                $this->direccion_fiscal['no_exterior'] = $datos_fiscales['numero_exterior'];
                $this->direccion_fiscal['no_interior'] = $datos_fiscales['numero_interior'];
                $this->direccion_fiscal['colonia'] = $datos_fiscales['colonia'];
                $this->direccion_fiscal['ciudad'] = $datos_fiscales['localidad'];
                $this->direccion_fiscal['delegacion'] = $datos_fiscales['municipio'];
                $this->direccion_fiscal['estado'] = $datos_fiscales['estado'];
                $this->regimen_fiscal_id = optional(RegimenFiscal::findByDescription($datos_fiscales['regimen_fiscal']))->id;
                $this->direccion_fiscal['estado_id'] = Estado::where('nombre', $datos_fiscales['estado'])->first()?->id;
                if ($this->direccion_fiscal['estado_id']) {
                    $this->direccion_fiscal['localidad_id'] = Localidad::where('estado_id', $this->direccion_fiscal['estado_id'])->where('nombre', $datos_fiscales['localidad'])->first()?->id;
                    $this->direccion_fiscal['municipio_id'] = Municipio::where('estado_id', $this->direccion_fiscal['estado_id'])->where('nombre', $datos_fiscales['municipio'])->first()?->id;
                }
                $this->regimen_fiscal_id = optional(RegimenFiscal::findByDescription($datos_fiscales['regimen_fiscal']))->id;
                $this->emit('show-toast', __('site.diners.save.fiscal_data_loaded'), 'success');
            } catch (Exception $e) {
                Log::error("cargando los datos fiscales desde documento fiscal. Error: {$e->getMessage()}");
                $this->emit('show-toast', __('site.diners.save.invalid_fiscal_document'), 'danger');
            }
        }
    }

    public function render()
    {
        return view('livewire.comensales.save');
    }

    public function getWithScopeProperty()
    {
        return $this->scope != null;
    }

    public function hydrate()
    {
        $this->dispatchBrowserEvent('reApplySelect2');
        $this->init();
    }

    public function updated()
    {
        $this->dispatchBrowserEvent('reApplySelect2');
        $this->init();
    }

    public function rules()
    {
        $collection = user()->cliente->comensales;
        $collection->each(function ($comensal) {
            $comensal = Cliente::decryptInfo($comensal);
        });
        return [
            'nombre_comercial' => ['required', new RuleUnique($collection, $this->comensal->id)],
            'con_facturacion' => ['nullable', 'boolean'],
            'razon_social' => ['required_if:con_facturacion,true', new RuleUnique($collection, $this->comensal->id)],
            'rfc' => ['required_if:con_facturacion,true', new RuleUnique($collection, $this->comensal->id), new RfcRule('ambas')],
            'correo' => ['required'],
            'telefono' => ['nullable'],
            'comentarios' => ['nullable'],
            'regimen_fiscal_id' => ['required_if:con_facturacion,true', new RfcYRegimenCoherentesRule($this->rfc)],
            'direccion_fiscal.codigo_postal' => ['required_if:con_facturacion,true'],
            'direccion_fiscal.calle' => 'nullable',
            'direccion_fiscal.no_exterior' => 'nullable',
            'direccion_fiscal.no_interior' => 'nullable',
            'direccion_fiscal.colonia' => 'nullable',
            'direccion_fiscal.localidad_id' => 'nullable',
            'direccion_fiscal.municipio_id' => 'nullable',
            'direccion_fiscal.estado_id' => 'nullable',
            'direccion_fiscal.referencia' => 'nullable'
        ];
    }

    public function messages()
    {
        return [
            'nombre_comercial.required' => 'Campo requerido',
            'razon_social.required_if' => 'Campo requerido',
            'rfc.required_if' => 'Campo requerido',
            'correo.required' => 'Campo requerido',
            'regimen_fiscal_id.required_if' => 'Campo requerido',
            'direccion_fiscal.codigo_postal.required_if' => 'Campo requerido.'
        ];
    }

    public function save()
    {
        $data = $this->validate(
            $this->rules(),
            // $this->messages()
        );
        DB::beginTransaction();
        try {
            $data['rfc'] = strtoupper(str_replace(' ', '', $data['rfc']));

            $comensalDB = $this->comensal->id ? null : Cliente::withTrashed()->where('rfc', $data['rfc'])->first();

            if (!$comensalDB)
                $comensalDB = $this->comensal;
            if ($comensalDB->trashed())
                $comensalDB->restore();

            $data['es_comensal'] = 1;
            $data = Cliente::encryptInfo($data);

            $comensalDB->fill(Arr::only($data, [
                'nombre_comercial',
                'razon_social',
                'rfc',
                'correo',
                'telefono',
                'es_comensal',
                'comentarios',
                'con_facturacion',
                'regimen_fiscal_id'
            ]))->save();

            if ($comensalDB->direccion_fiscal()->exists()) {
                $comensalDB->direccion_fiscal->fill([
                    'calle' => $data['direccion_fiscal']['calle'],
                    'no_exterior' => $data['direccion_fiscal']['no_exterior'],
                    'no_interior' => $data['direccion_fiscal']['no_interior'],
                    'codigo_postal' => $data['direccion_fiscal']['codigo_postal'],
                    'colonia' => $data['direccion_fiscal']['colonia'],
                    'localidad_id' => $data['direccion_fiscal']['localidad_id'] ? $data['direccion_fiscal']['localidad_id'] : null,
                    'municipio_id' => $data['direccion_fiscal']['municipio_id'] ? $data['direccion_fiscal']['municipio_id'] : null,
                    'estado_id' => $data['direccion_fiscal']['estado_id'] ? $data['direccion_fiscal']['estado_id'] : null,
                    'referencia' => $data['direccion_fiscal']['referencia'],
                ]);
                if (count($comensalDB->direccion_fiscal->getDirty()) > 0) {
                    $attributes = Arr::except($comensalDB->direccion_fiscal->getDirty(), ['created_at', 'updated_at']);
                    if ($comensalDB->rfc) {
                        $log = __('site.diners.save.address_updated_rfc', ['rfc' => $comensalDB->rfc]);
                    } else {
                        $log = __('site.diners.save.address_updated_commercial_name', ['nombre_comercial' => $comensalDB->nombre_comercial]);
                    }
                    activity(__("site.diners.save.address_updated_log"))
                        ->on($comensalDB->direccion_fiscal)
                        ->event('updated')
                        ->withProperty('attributes', Direccion::parseData($attributes))
                        ->withProperty('old', Direccion::parseData(Arr::only($comensalDB->direccion_fiscal->getOriginal(), array_keys($attributes))))
                        ->log($log);
                    $comensalDB->direccion_fiscal->save();
                }
            } else {
                $dir = Direccion::create([
                    'calle' => $data['direccion_fiscal']['calle'],
                    'no_exterior' => $data['direccion_fiscal']['no_exterior'],
                    'no_interior' => $data['direccion_fiscal']['no_interior'],
                    'codigo_postal' => $data['direccion_fiscal']['codigo_postal'],
                    'colonia' => $data['direccion_fiscal']['colonia'],
                    'localidad_id' => $data['direccion_fiscal']['localidad_id'] ? $data['direccion_fiscal']['localidad_id'] : null,
                    'municipio_id' => $data['direccion_fiscal']['municipio_id'] ? $data['direccion_fiscal']['municipio_id'] : null,
                    'estado_id' => $data['direccion_fiscal']['estado_id'] ? $data['direccion_fiscal']['estado_id'] : null,
                    'referencia' => $data['direccion_fiscal']['referencia'],
                ]);
                $comensalDB->direccion_fiscal_id = $dir->id;
                $comensalDB->save();

                if ($comensalDB->rfc) {
                    $log = __('site.diners.save.address_created_rfc', ['rfc' => $comensalDB->rfc]);
                } else {
                    $log = __('site.diners.save.address_created_commercial_name', ['nombre_comercial' => $comensalDB->nombre_comercial]);
                }

                activity(__("site.diners.save.address_created_log"))
                    ->on($dir)
                    ->event('created')
                    ->withProperties(Direccion::parseData(Arr::except($dir->toArray(), ['updated_at'])))
                    ->log($log);
            }

            user()->cliente->comensales()->syncWithoutDetaching([$comensalDB->id => ['activo' => 1]]);
            $this->emit('show-toast', __('site.diners.save.client_saved_successfully'), 'success');
            if ($this->scope) {
                if ($comensalDB->wasRecentlyCreated) {
                    $this->emitTo($this->scope, 'cliente-created', $comensalDB->id);
                } else {
                    $this->emitTo($this->scope, 'cliente-updated', $comensalDB->id);
                }
            } else {
                $this->emit('$refresh');
            }
            DB::commit();
            $this->emit('closeModal');
        } catch (\Exception $e) {
            DB::rollBack();
            Log::error($e->getMessage());
            $this->emit('show-toast', __('site.diners.save.client_save_failed'), 'danger');
        }
    }

    public function init()
    {
        if (user()->cannot($this->comensal->id ? 'updateComensal' : 'createComensal', $this->comensal->id ? $this->comensal : [Cliente::class])) {
            $this->emit('show-toast', __('site.common.client_no_permissions'), 'danger');
            $this->emit('closeModal');
            return;
        }

        if ($this->direccion_fiscal['estado_id']) {
            $estado = Estado::find($this->direccion_fiscal['estado_id']);
            $this->dispatchBrowserEvent("set-data-direccion_fiscal-estado_id", ['data' => [$estado->only('id', 'text')], 'term' => '', 'value' => $estado->id]);
        }
        if ($this->direccion_fiscal['localidad_id']) {
            $localidad = Localidad::find($this->direccion_fiscal['localidad_id']);
            $this->dispatchBrowserEvent("set-data-direccion_fiscal-localidad_id", ['data' => [$localidad->only('id', 'text')], 'term' => '', 'value' => $localidad->id]);
        }
        if ($this->direccion_fiscal['municipio_id']) {
            $municipio = Municipio::find($this->direccion_fiscal['municipio_id']);
            $this->dispatchBrowserEvent("set-data-direccion_fiscal-municipio_id", ['data' => [$municipio->only('id', 'text')], 'term' => '', 'value' => $municipio->id]);
        }
    }
}
