<?php

namespace App\Http\Livewire\Comensales;

use App\Http\Livewire\Layouts\Modal;
use App\Models\RegimenFiscal;
use App\Models\Direccion;
use App\Models\Estado;
use App\Models\Localidad;
use App\Models\Municipio;
use App\Models\Cliente;
use App\Rules\RfcRule;
use App\Rules\RfcYRegimenCoherentesRule;
use App\Rules\RuleUnique;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class Save extends Modal
{
    public $scope = null;
    public Cliente $comensal;
    public $nombre_comercial;
    public $razon_social;
    public $rfc;
    public $correo;
    public $telefono;
    public $comentarios;
    public $regimen_fiscal_id;
    public $direccion_fiscal;

    public $regimenesFiscales = [];
    public $estados = [];

    protected $listeners = ['$refresh'];

    public function mount()
    {
        $this->regimenesFiscales = RegimenFiscal::orderBy('codigo')->get()->map->only('label', 'value');

        if (!isset($this->comensal)) {
            $this->comensal = new Cliente();
        } else {
            $this->comensal = Cliente::decryptInfo($this->comensal);
            $this->nombre_comercial = $this->comensal->nombre_comercial;
            $this->razon_social = $this->comensal->razon_social;
            $this->rfc = $this->comensal->rfc;
            $this->correo = $this->comensal->correo;
            $this->telefono = $this->comensal->telefono;
            $this->regimen_fiscal_id = $this->comensal->regimen_fiscal_id;
        }
        $this->direccion_fiscal = $this->comensal->direccion_fiscal->toArray();
        $this->estados = get_estados_mexico();
    }

    public static function modalMaxWidthClass(): string
    {
        return 'modal-xl'; // TODO: Change the autogenerated stub
    }

    public function render()
    {
        return view('livewire.comensales.save');
    }

    public function getWithScopeProperty()
    {
        return $this->scope != null;
    }

    public function hydrate()
    {
        $this->dispatchBrowserEvent('reApplySelect2');
        $this->init();
    }

    public function updated()
    {
        $this->dispatchBrowserEvent('reApplySelect2');
        $this->init();
    }

    public function rules()
    {
        $collection = DB::table('tb_clientes')
            ->select('id', 'nombre_comercial', 'razon_social', 'rfc', DB::raw('0 as decrypted'))
            ->get();
        $collection->map(function ($comensal) {
            $comensal = Cliente::decryptInfo($comensal);
        });
        return [
            'nombre_comercial' => ['required', new RuleUnique($collection, $this->comensal->id)],
            'razon_social' => ['required', new RuleUnique($collection, $this->comensal->id)],
            'rfc' => ['required', new RuleUnique($collection, $this->comensal->id), new RfcRule('ambas')],
            'correo' => ['required'],
            'telefono' => ['nullable'],
            'comentarios' => ['nullable'],
            'regimen_fiscal_id' => ['nullable', new RfcYRegimenCoherentesRule($this->rfc)],
            'direccion_fiscal.codigo_postal' => ['required'],
            'direccion_fiscal.calle' => 'nullable',
            'direccion_fiscal.no_exterior' => 'nullable',
            'direccion_fiscal.no_interior' => 'nullable',
            'direccion_fiscal.colonia' => 'nullable',
            'direccion_fiscal.localidad_id' => 'nullable',
            'direccion_fiscal.municipio_id' => 'nullable',
            'direccion_fiscal.estado_id' => 'nullable',
            'direccion_fiscal.referencia' => 'nullable'
        ];
    }

    public function messages()
    {
        return [
            'nombre_comercial.required' => 'Campo requerido',
            'razon_social.required' => 'Campo requerido',
            'rfc.required' => 'Campo requerido',
            'correo.required' => 'Campo requerido',
            'direccion_fiscal.codigo_postal.required' => 'Campo requerido.'
        ];
    }

    public function save()
    {
        $data = $this->validate($this->rules(), $this->messages());
        DB::beginTransaction();
        try {
            $data['rfc'] = strtoupper(str_replace(' ', '', $data['rfc']));
            $data['es_comensal'] = 1;
            $data = Cliente::encryptInfo($data);

            $this->comensal->fill(Arr::only($data, [
                'nombre_comercial',
                'razon_social',
                'rfc',
                'correo',
                'telefono',
                'es_comensal',
                'regimen_fiscal_id'
            ]))->save();

            if ($this->comensal->direccion_fiscal()->exists()) {
                $this->comensal->direccion_fiscal->fill([
                    'calle' => $data['direccion_fiscal']['calle'],
                    'no_exterior' => $data['direccion_fiscal']['no_exterior'],
                    'no_interior' => $data['direccion_fiscal']['no_interior'],
                    'codigo_postal' => $data['direccion_fiscal']['codigo_postal'],
                    'colonia' => $data['direccion_fiscal']['colonia'],
                    'localidad_id' => $data['direccion_fiscal']['localidad_id'] ? $data['direccion_fiscal']['localidad_id'] : null,
                    'municipio_id' => $data['direccion_fiscal']['municipio_id'] ? $data['direccion_fiscal']['municipio_id'] : null,
                    'estado_id' => $data['direccion_fiscal']['estado_id'] ? $data['direccion_fiscal']['estado_id'] : null,
                    'referencia' => $data['direccion_fiscal']['referencia'],
                ]);
                if (count($this->comensal->direccion_fiscal->getDirty()) > 0) {
                    $attributes = Arr::except($this->comensal->direccion_fiscal->getDirty(), ['created_at', 'updated_at']);
                    activity('Dirección Fiscal de Comensal Actualizada')
                        ->on($this->comensal->direccion_fiscal)
                        ->event('updated')
                        ->withProperty('attributes', Direccion::parseData($attributes))
                        ->withProperty('old', Direccion::parseData(Arr::only($this->comensal->direccion_fiscal->getOriginal(), array_keys($attributes))))
                        ->log('La Dirección Fiscal del Comensal con RFC:' . $this->comensal->rfc . ' ha sido actualizada.');
                    $this->comensal->direccion_fiscal->save();
                }
            } else {
                $dir = Direccion::create([
                    'calle' => $data['direccion_fiscal']['calle'],
                    'no_exterior' => $data['direccion_fiscal']['no_exterior'],
                    'no_interior' => $data['direccion_fiscal']['no_interior'],
                    'codigo_postal' => $data['direccion_fiscal']['codigo_postal'],
                    'colonia' => $data['direccion_fiscal']['colonia'],
                    'localidad_id' => $data['direccion_fiscal']['localidad_id'] ? $data['direccion_fiscal']['localidad_id'] : null,
                    'municipio_id' => $data['direccion_fiscal']['municipio_id'] ? $data['direccion_fiscal']['municipio_id'] : null,
                    'estado_id' => $data['direccion_fiscal']['estado_id'] ? $data['direccion_fiscal']['estado_id'] : null,
                    'referencia' => $data['direccion_fiscal']['referencia'],
                ]);
                $this->comensal->direccion_fiscal_id = $dir->id;
                $this->comensal->save();

                activity("Dirección Fiscal de Comensal Creada")
                    ->on($dir)
                    ->event('created')
                    ->withProperties(Direccion::parseData(Arr::except($dir->toArray(), ['updated_at'])))
                    ->log('La Dirección Fiscal del Comensal con RFC: ' . $this->comensal->rfc . ' ha sido creada.');
            }

            $this->emit('show-toast', 'Cliente guardado.');
            if ($this->scope) {
                if ($this->comensal->wasRecentlyCreated) {
                    $this->emitTo($this->scope, 'cliente-created', $this->comensal->id);
                } else {
                    $this->emitTo($this->scope, 'cliente-updated', $this->comensal->id);
                }
            } else {
                $this->emit('$refresh');
            }
            DB::commit();
            $this->emit('closeModal');
        } catch (\Exception $e) {
            DB::rollBack();
            Log::error($e->getMessage());
            $this->emit('show-toast', 'Ocurrio un error. ' . $e->getMessage(), 'danger');
        }
    }

    public function init()
    {
        if ($this->direccion_fiscal['estado_id']) {
            $estado = Estado::find($this->direccion_fiscal['estado_id']);
            $this->dispatchBrowserEvent("set-data-direccion_fiscal-estado_id", ['data' => [$estado->only('id', 'text')], 'term' => '', 'value' => $estado->id]);
        }
        if ($this->direccion_fiscal['localidad_id']) {
            $localidad = Localidad::find($this->direccion_fiscal['localidad_id']);
            $this->dispatchBrowserEvent("set-data-direccion_fiscal-localidad_id", ['data' => [$localidad->only('id', 'text')], 'term' => '', 'value' => $localidad->id]);
        }
        if ($this->direccion_fiscal['municipio_id']) {
            $municipio = Municipio::find($this->direccion_fiscal['municipio_id']);
            $this->dispatchBrowserEvent("set-data-direccion_fiscal-municipio_id", ['data' => [$municipio->only('id', 'text')], 'term' => '', 'value' => $municipio->id]);
        }
    }
}
