<?php

namespace App\Http\Livewire\Sucursales;

use App\Http\Livewire\Layouts\Modal;
use App\Models\Sucursal;
use App\Models\SucursalFormaPago;
use App\Models\TipoCambio;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;

class Configuraciones extends Modal
{
    public Sucursal $sucursal;
    public $tipo_cambio = [
        'id' => null,
        'tasa' => '',
        'from_id' => null,
        'to_id' => null
    ];
    public $moneda_sucursal;
    public $tipos_cambio = [];
    public $monedas = [];

    public $modalFormaPagoSaveClass = '';
    public $modalDeleteFormaPagoClass = '';
    public $modalRestoreFormaPagoClass = '';

    protected $listeners = ['$refresh', 'tipo-cambio-deleted' => 'loadTiposCambio'];

    public function mount()
    {
        $this->moneda_sucursal = $this->sucursal->moneda_base_id;
        $this->monedas = DB::table('tb_monedas')
            ->select('id as value', 'acronimo as label')
            ->whereNull('deleted_at')
            ->get()
            ->map(function ($value, $key) {
                return (array)$value;
            })->toArray();
        $this->loadTiposCambio();
    }

    public function hydrate()
    {
        $this->dispatchBrowserEvent('reApplySelect2');
        $this->loadTiposCambio();
    }

    public function updated($value)
    {
        if (in_array($value, ['moneda_sucursal', 'moneda_facturacion'])) {
            $this->save($value);
        }
    }

    public function getNombreSucursalProperty()
    {
        return Crypt::decrypt($this->sucursal->nombre_comercial);
    }

    public static function modalMaxWidthClass(): string
    {
        return 'modal-xl'; // TODO: Change the autogenerated stub
    }

    public function render()
    {
        return view('livewire.sucursales.configuraciones');
    }

    public function init()
    {
        if (user()->cannot('setConfigs', $this->sucursal)) {
            $this->emit('show-toast', 'No tiene permisos para realizar estar acción.', 'danger');
            $this->emit('closeModal');
            return;
        }
    }

    public function loadTiposCambio()
    {
        $this->tipos_cambio = DB::table('tb_tipo_cambios as tc')
            ->select(['tc.id', 'tc.tasa', 'c_from.acronimo as from_moneda', 'c_to.acronimo as to_moneda'])
            ->leftJoin('tb_monedas as c_from', 'c_from.id', '=', 'tc.from_id')
            ->leftJoin('tb_monedas as c_to', 'c_to.id', '=', 'tc.to_id')
            ->where('tc.sucursal_id', $this->sucursal->id)
            ->get()->map(function ($element) {
                return (array)$element;
            })->toArray();
    }

    public function save($key)
    {
        if ($key == 'moneda_sucursal') {
            if (!$this->{$key}) {
                $this->emit('show-toast', 'Hay errores en el formulario.', 'danger');
                $this->addError($key, 'Campo obligatorio.');
                $this->{$key} = $this->sucursal->moneda_base_id;
                return;
            }
            DB::table('tb_sucursales')->where('id', $this->sucursal->id)->update(['moneda_base_id' => $this->{$key}]);
        }

        $this->emit('show-toast', 'Configuración actualizada!');
        $this->emit('$refresh');
    }

    public function saveTasa()
    {
        $data = $this->validate([
            'tipo_cambio.tasa' => ['required', 'numeric', 'min:0.0001'],
            'tipo_cambio.from_id' => ['required', 'exists:tb_monedas,id'],
            'tipo_cambio.to_id' => ['required', 'exists:tb_monedas,id']
        ],
        // [
        //     'tipo_cambio.tasa.required' => 'Campo obligatorio.',
        //     'tipo_cambio.tasa.numeric' => 'El valor debe ser un número.',
        //     'tipo_cambio.tasa.min' => 'El valor debe ser al menos :min.',
        //     'tipo_cambio.from_id.required' => 'Campo obligatorio.',
        //     'tipo_cambio.from_id.exists' => 'La moneda base seleccionada no es válida.',
        //     'tipo_cambio.to_id.required' => 'Campo obligatorio.',
        //     'tipo_cambio.to_id.exists' => 'La moneda destino seleccionada no es válida.'
        // ]
        );

        TipoCambio::updateOrCreate(
            [
                'sucursal_id' => $this->sucursal->id,
                'cliente_id' => $this->sucursal->cliente_id,
                'from_id' => $data['tipo_cambio']['from_id'],
                'to_id' => $data['tipo_cambio']['to_id']
            ],
            [
                'tasa' => $data['tipo_cambio']['tasa']
            ]
        );
        $this->loadTiposCambio();
        $this->emit('show-toast', 'Tasa de cambio guardada!');
        $this->emit('$refresh');
    }

    public function editTasa($id)
    {
        $tipo_cambio = TipoCambio::find($id);
        if (!$tipo_cambio || $tipo_cambio->sucursal_id != $this->sucursal->id) {
            $this->emit('show-toast', 'Tasa de cambio no encontrada.', 'danger');
            return;
        }
        $this->tipo_cambio = [
            'id' => $tipo_cambio->id,
            'tasa' => $tipo_cambio->ratetasa,
            'from_id' => $tipo_cambio->from_id,
            'to_id' => $tipo_cambio->to_id
        ];
    }
}
