<?php

namespace App\Http\Livewire\Sucursales;

use App\Http\Livewire\Layouts\Modal;
use App\Models\RegimenFiscal;
use App\Models\Direccion;
use App\Models\Estado;
use App\Models\Localidad;
use App\Models\Municipio;
use App\Models\Cliente;
use App\Models\Sucursal;
use App\Models\Suscripcion;
use App\Rules\RfcRule;
use App\Rules\RfcYRegimenCoherentesRule;
use App\Rules\RuleUnique;
use Exception;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Livewire\WithFileUploads;
use Smalot\PdfParser\Parser;

class Save extends Modal
{
    use WithFileUploads;

    public $scope = null;
    public Sucursal $sucursal;
    public $nombre_comercial;
    public $razon_social;
    public $rfc;
    public $correo;
    public $telefono;
    public $tipo_vigencia_ticket_facturacion;
    public $dias_vigencia;
    public $cliente_id;
    public $suscripcion_id;
    public $regimen_fiscal_id;
    public $direccion_fiscal;
    public $logo;
    public $logo_src;

    public $regimenesFiscales = [];
    public $suscripciones = [];
    public $estados = [];
    public $tomar_datos_fiscales_de_empresa_matriz = false;
    public $con_facturacion;
    public $from_subscription = false;
    public $constancia_fiscal;
    public $tiposVigenciaTicketFacturacion = ['last_day_month', 'days_number_after_emitted', 'days_number_next_month'];

    protected $listeners = ['$refresh'];

    public function mount()
    {
        $this->regimenesFiscales = RegimenFiscal::orderBy('codigo')->get()->map->only(['label', 'value']);

        if (!isset($this->sucursal)) {
            $this->sucursal = new Sucursal();
            if (user()->is_admin)
                $this->cliente_id = user()->cliente_id;
        } else {
            $this->sucursal = Sucursal::decryptInfo($this->sucursal);
            $this->nombre_comercial = $this->sucursal->nombre_comercial;
            $this->razon_social = $this->sucursal->razon_social;
            $this->rfc = $this->sucursal->rfc;
            $this->correo = $this->sucursal->correo;
            $this->telefono = $this->sucursal->telefono;
            $this->tipo_vigencia_ticket_facturacion = $this->sucursal->tipo_vigencia_ticket_facturacion;
            $this->dias_vigencia = $this->sucursal->dias_vigencia;
            $this->regimen_fiscal_id = $this->sucursal->regimen_fiscal_id;
            $this->cliente_id = $this->sucursal->cliente_id;
            $this->suscripcion_id = $this->sucursal->suscripcion_id;
            $this->logo = $this->sucursal->logo_uri;
            $this->logo_src = $this->logo;
        }
        $this->direccion_fiscal = $this->sucursal->direccion_fiscal->toArray();
        $this->estados = get_estados_mexico();

        if ($this->cliente_id) {
            $cliente = Cliente::decryptInfo(Cliente::find($this->cliente_id));

            $this->tomar_datos_fiscales_de_empresa_matriz = $this->rfc &&
                $this->rfc === $cliente->rfc &&
                $this->nombre_comercial &&
                $this->nombre_comercial === $cliente->nombre_comercial &&
                $this->razon_social &&
                $this->razon_social === $cliente->razon_social &&
                $this->regimen_fiscal_id &&
                $this->regimen_fiscal_id === $cliente->regimen_fiscal_id;
            $this->con_facturacion = $cliente->con_facturacion;

            $this->loadSuscripciones();
        }
    }

    public static function modalMaxWidthClass(): string
    {
        return 'modal-xl'; // TODO: Change the autogenerated stub
    }

    public function updatedConstanciaFiscal($value)
    {
        if ($value) {
            if ($value->getMimeType() != 'application/pdf') {
                $this->emit('show-toast', 'Seleccione el fichero correcto. Solo se aceptan archivos del tipo PDF.', 'danger');
                return;
            }

            try {
                $parser = new Parser();
                $content = file_get_contents($value->getRealPath());
                $pdf = $parser->parseContent($content);
                $text = $pdf->getText();

                $datos_fiscales = extraer_datos_fiscales($text);

                if ($datos_fiscales['tipo_persona'] == 'fisica') {
                    $nombre = $datos_fiscales['nombre'] . ' ' . $datos_fiscales['apellido_paterno'] . ' ' . $datos_fiscales['apellido_materno'];
                    $this->razon_social = $nombre;
                    $this->nombre_comercial = $nombre;
                } else {
                    $this->razon_social = $datos_fiscales['razon_social'];
                    $this->nombre_comercial = $datos_fiscales['nombre_comercial'];
                }
                $this->rfc = $datos_fiscales['rfc'];
                $this->direccion_fiscal['codigo_postal'] = $datos_fiscales['codigo_postal'];
                $this->direccion_fiscal['calle'] = $datos_fiscales['calle'];
                $this->direccion_fiscal['no_exterior'] = $datos_fiscales['numero_exterior'];
                $this->direccion_fiscal['no_interior'] = $datos_fiscales['numero_interior'];
                $this->direccion_fiscal['colonia'] = $datos_fiscales['colonia'];
                $this->direccion_fiscal['ciudad'] = $datos_fiscales['localidad'];
                $this->direccion_fiscal['delegacion'] = $datos_fiscales['municipio'];
                $this->direccion_fiscal['estado'] = $datos_fiscales['estado'];
                $this->regimen_fiscal_id = optional(RegimenFiscal::findByDescription($datos_fiscales['regimen_fiscal']))->id;
                $this->direccion_fiscal['estado_id'] = Estado::where('nombre', $datos_fiscales['estado'])->first()?->id;
                if ($this->direccion_fiscal['estado_id']) {
                    $this->direccion_fiscal['localidad_id'] = Localidad::where('estado_id', $this->direccion_fiscal['estado_id'])->where('nombre', $datos_fiscales['localidad'])->first()?->id;
                    $this->direccion_fiscal['municipio_id'] = Municipio::where('estado_id', $this->direccion_fiscal['estado_id'])->where('nombre', $datos_fiscales['municipio'])->first()?->id;
                }
                $this->regimen_fiscal_id = optional(RegimenFiscal::findByDescription($datos_fiscales['regimen_fiscal']))->id;
                $this->tomar_datos_fiscales_de_empresa_matriz = false;
                $this->emit('show-toast', 'Datos cargados correctamente.', 'success');
            } catch (Exception $e) {
                $this->emit('show-toast', 'Lo sentimos no se pudo realizar la carga de información. Documento inválido o corrupto.', 'danger');
            }
        }
    }

    public function render()
    {
        return view('livewire.sucursales.save');
    }

    public function getWithScopeProperty()
    {
        return $this->scope != null;
    }

    public function hydrate()
    {
        $this->dispatchBrowserEvent('reApplySelect2');
        $this->init();
    }

    public function updated()
    {
        $this->dispatchBrowserEvent('reApplySelect2');
        $this->init();
    }

    public function updatedClienteId($value)
    {
        $this->tomar_datos_fiscales_de_empresa_matriz = false;
        $this->con_facturacion = false;
        $this->suscripcion_id = null;
        $this->suscripciones = [];
        if ($value) {
            $cliente = Cliente::decryptInfo(Cliente::find($value));

            $this->tomar_datos_fiscales_de_empresa_matriz = $this->rfc &&
                $this->rfc === $cliente->rfc &&
                $this->nombre_comercial &&
                $this->nombre_comercial === $cliente->nombre_comercial &&
                $this->razon_social &&
                $this->razon_social === $cliente->razon_social &&
                $this->regimen_fiscal_id &&
                $this->regimen_fiscal_id === $cliente->regimen_fiscal_id;
            $this->con_facturacion = $cliente->con_facturacion;

            $this->loadSuscripciones();
        }
    }

    public function updatedTomarDatosFiscalesDeEmpresaMatriz($value)
    {
        if ($value) {
            $empresa = Cliente::decryptInfo(Cliente::find($this->cliente_id));
            $this->razon_social = $empresa->razon_social;
            $this->rfc = $empresa->rfc;
        }
    }

    public function rules()
    {
        $collection = DB::table('tb_sucursales')
            ->select('id', 'nombre_comercial', 'razon_social', 'rfc', DB::raw('0 as decrypted'))
            ->get();
        $collection->each(function ($sucursal) {
            $sucursal = Sucursal::decryptInfo($sucursal);
        });


        $rules = [
            'nombre_comercial' => ['required'],
            'con_facturacion' => ['nullable', 'boolean'],
            'razon_social' => ['required_if:con_facturacion,true'],
            'rfc' => ['required_if:con_facturacion,true', new RfcRule('ambas')],
            'correo' => ['required'],
            'telefono' => ['nullable'],
            'tipo_vigencia_ticket_facturacion' => ['nullable', 'required_if:con_facturacion,true'],
            'cliente_id' => ['required', 'exists:tb_clientes,id'],
            'suscripcion_id' => ['nullable', 'exists:tb_suscripciones,id'],
            'regimen_fiscal_id' => ['nullable', 'required_if:con_facturacion,true', 'exists:tb_regimen_fiscales,id', new RfcYRegimenCoherentesRule($this->rfc)],
            'direccion_fiscal.codigo_postal' => ['nullable', 'required_if:con_facturacion,true'],
            'direccion_fiscal.calle' => 'nullable',
            'direccion_fiscal.no_exterior' => 'nullable',
            'direccion_fiscal.no_interior' => 'nullable',
            'direccion_fiscal.colonia' => 'nullable',
            'direccion_fiscal.localidad_id' => 'nullable',
            'direccion_fiscal.municipio_id' => 'nullable',
            'direccion_fiscal.estado_id' => 'nullable',
            'direccion_fiscal.referencia' => 'nullable'
        ];

        if (in_array($this->tipo_vigencia_ticket_facturacion, ['days_number_after_emitted', 'days_number_next_month'])) {
            $rules = array_merge($rules, ['dias_vigencia' => ['required', 'numeric', 'min:1']]);
        } else {
            $rules = array_merge($rules, ['dias_vigencia' => ['nullable']]);
            $this->dias_vigencia = null;
        }

        return $rules;
    }

    public function messages()
    {
        return [
            'nombre_comercial.required' => 'Campo requerido',
            'razon_social.required_if' => 'Campo requerido',
            'rfc.required_if' => 'Campo requerido',
            'correo.required' => 'Campo requerido',
            'tipo_vigencia_ticket_facturacion.required_if' => 'Campo requerido',
            'dias_vigencia.required' => 'Campo requerido',
            'dias_vigencia.numeric' => 'Campo numérico',
            'dias_vigencia.min' => 'Entre un valor superior',
            'cliente_id.required' => 'Campo requerido',
            'cliente_id.exists' => 'Cliente no encontrado',
            'regimen_fiscal_id.required_if' => 'Campo requerido',
            'regimen_fiscal_id.exists' => 'Régimen Fiscal no encontrado',
            'direccion_fiscal.codigo_postal.required_if' => 'Campo requerido.'
        ];
    }

    public function save()
    {
        $data = $this->validate(
            $this->rules(),
            // $this->messages()
        );
        DB::beginTransaction();
        try {
            $data['rfc'] = strtoupper(str_replace(' ', '', $data['rfc']));
            $data = Sucursal::encryptInfo($data);

            $this->sucursal->fill(Arr::only($data, [
                'nombre_comercial',
                'razon_social',
                'rfc',
                'correo',
                'telefono',
                'tipo_vigencia_ticket_facturacion',
                'dias_vigencia',
                'cliente_id',
                'suscripcion_id',
                'regimen_fiscal_id'
            ]))->save();

            if ($this->sucursal->direccion_fiscal()->exists()) {
                $this->sucursal->direccion_fiscal->fill([
                    'calle' => $data['direccion_fiscal']['calle'],
                    'no_exterior' => $data['direccion_fiscal']['no_exterior'],
                    'no_interior' => $data['direccion_fiscal']['no_interior'],
                    'codigo_postal' => $data['direccion_fiscal']['codigo_postal'],
                    'colonia' => $data['direccion_fiscal']['colonia'],
                    'localidad_id' => $data['direccion_fiscal']['localidad_id'],
                    'municipio_id' => $data['direccion_fiscal']['municipio_id'],
                    'estado_id' => $data['direccion_fiscal']['estado_id'],
                    'referencia' => $data['direccion_fiscal']['referencia'],
                ]);
                if (count($this->sucursal->direccion_fiscal->getDirty()) > 0) {
                    $attributes = Arr::except($this->sucursal->direccion_fiscal->getDirty(), ['created_at', 'updated_at']);
                    activity('Dirección Fiscal de Sucursal Actualizada')
                        ->on($this->sucursal->direccion_fiscal)
                        ->event('updated')
                        ->withProperty('attributes', Direccion::parseData($attributes))
                        ->withProperty('old', Direccion::parseData(Arr::only($this->sucursal->direccion_fiscal->getOriginal(), array_keys($attributes))))
                        ->log('La Dirección Fiscal de la Sucursal con RFC: ' . $this->sucursal->rfc . ' ha sido actualizada.');
                    $this->sucursal->direccion_fiscal->save();
                }
            } else {
                $dir = Direccion::create([
                    'calle' => $data['direccion_fiscal']['calle'],
                    'no_exterior' => $data['direccion_fiscal']['no_exterior'],
                    'no_interior' => $data['direccion_fiscal']['no_interior'],
                    'codigo_postal' => $data['direccion_fiscal']['codigo_postal'],
                    'colonia' => $data['direccion_fiscal']['colonia'],
                    'localidad_id' => $data['direccion_fiscal']['localidad_id'],
                    'municipio_id' => $data['direccion_fiscal']['municipio_id'],
                    'estado_id' => $data['direccion_fiscal']['estado_id'],
                    'referencia' => $data['direccion_fiscal']['referencia'],
                ]);
                $this->sucursal->direccion_fiscal_id = $dir->id;
                $this->sucursal->save();

                activity("Dirección Fiscal de Sucursal Creada")
                    ->on($dir)
                    ->event('created')
                    ->withProperties(Direccion::parseData(Arr::except($dir->toArray(), ['updated_at'])))
                    ->log('La Dirección Fiscal de la Sucursal con RFC: ' . $this->sucursal->rfc . ' ha sido creada.');
            }

            if ($this->logo && !is_string($this->logo)) {
                $ext = $this->logo->extension();
                $nombre = Str::uuid() . ".$ext";
                $this->logo->storeAs('', $nombre, 'logos');
                $this->sucursal->logo = $nombre;
            } else if ($this->logo == '' || $this->logo == null) {
                if ($this->sucursal->logo && Storage::disk('logos')->exists($this->sucursal->logo)) {
                    Storage::disk('logos')->delete($this->sucursal->logo);
                }
                $this->sucursal->logo = null;
            }
            $this->sucursal->save();

            $this->emit('show-toast', 'Sucursal guardada.');
            if ($this->scope) {
                if ($this->sucursal->wasRecentlyCreated) {
                    $this->emitTo($this->scope, 'sucursal-created', $this->sucursal->id);
                } else {
                    $this->emitTo($this->scope, 'sucursal-updated', $this->sucursal->id);
                }
            } else {
                $this->emit('$refresh');
            }
            DB::commit();

            $this->emit('closeModal');
        } catch (\Exception $e) {
            DB::rollBack();
            Log::error($e->getMessage());
            $this->emit('show-toast', 'Ocurrio un error. ' . $e->getMessage(), 'danger');
        }
    }

    public function init()
    {
        if (user()->cannot($this->sucursal->exists() ? 'update' : 'create', $this->sucursal->exists() ? $this->sucursal : [Sucursal::class])) {
            $this->emit('show-toast', 'No tiene permisos para realizar estar acción.', 'danger');
            $this->emit('closeModal');
            return;
        }

        if ($this->cliente_id) {
            $cliente = Cliente::find($this->cliente_id);
            $nombre = Crypt::decrypt($cliente->nombre_comercial);
            $this->dispatchBrowserEvent("set-data-cliente_id", ['data' => [['id' => $cliente->id, 'text' => $nombre]], 'term' => '', 'value' => $cliente->id]);
        }
        if ($this->direccion_fiscal['estado_id']) {
            $estado = Estado::find($this->direccion_fiscal['estado_id']);
            $this->dispatchBrowserEvent("set-data-direccion_fiscal-estado_id", ['data' => [$estado->only('id', 'text')], 'term' => '', 'value' => $estado->id]);
        }
        if ($this->direccion_fiscal['localidad_id']) {
            $localidad = Localidad::find($this->direccion_fiscal['localidad_id']);
            $this->dispatchBrowserEvent("set-data-direccion_fiscal-localidad_id", ['data' => [$localidad->only('id', 'text')], 'term' => '', 'value' => $localidad->id]);
        }
        if ($this->direccion_fiscal['municipio_id']) {
            $municipio = Municipio::find($this->direccion_fiscal['municipio_id']);
            $this->dispatchBrowserEvent("set-data-direccion_fiscal-municipio_id", ['data' => [$municipio->only('id', 'text')], 'term' => '', 'value' => $municipio->id]);
        }
    }

    public function loadSuscripciones()
    {
        Suscripcion::where('estado', 'ACTIVA')->where('cliente_id', $this->cliente_id)->withCount('sucursales')->each(function (Suscripcion $suscripcion) {
            if (
                $suscripcion->sucursales_count < $suscripcion->cant_sucursales
                || $suscripcion->id == $this->suscripcion_id
            ) {
                $this->suscripciones[] = $suscripcion->only(['value', 'label']);
            }
        });
    }

    public function removeLogo()
    {
        $this->logo = '';
    }

    public function getHasLogoProperty()
    {
        return $this->logo != '';
    }
}
