<?php

namespace App\Http\Livewire\Clientes;

use App\Http\Livewire\Layouts\Modal;
use App\Models\RegimenFiscal;
use App\Models\Direccion;
use App\Models\Estado;
use App\Models\Localidad;
use App\Models\Municipio;
use App\Models\Cliente;
use App\Rules\RfcRule;
use App\Rules\RfcYRegimenCoherentesRule;
use App\Rules\RuleUnique;
use Exception;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Livewire\WithFileUploads;
use Smalot\PdfParser\Parser;

class Save extends Modal
{
    use WithFileUploads;
    public $scope = null;
    public Cliente $cliente;
    public $nombre_comercial;
    public $razon_social;
    public $rfc;
    public $correo;
    public $telefono;
    public $contacto_nombre;
    public $contacto_correo;
    public $contacto_telefono;
    public $contacto_cargo;
    public $comentarios;
    public $con_facturacion;
    public $es_cliente_fiel;
    public $regimen_fiscal_id;
    public $direccion_fiscal;
    public $constancia_fiscal;

    public $regimenesFiscales = [];
    public $estados = [];

    protected $listeners = ['$refresh'];

    public function mount()
    {
        $this->regimenesFiscales = RegimenFiscal::orderBy('codigo')->get()->map->only(['label', 'value']);

        if (!isset($this->cliente)) {
            $this->cliente = new Cliente();
        } else {
            $this->cliente = Cliente::decryptInfo($this->cliente);
            $this->nombre_comercial = $this->cliente->nombre_comercial;
            $this->razon_social = $this->cliente->razon_social;
            $this->rfc = $this->cliente->rfc;
            $this->correo = $this->cliente->correo;
            $this->telefono = $this->cliente->telefono;
            $this->contacto_nombre = $this->cliente->contacto_nombre;
            $this->contacto_correo = $this->cliente->contacto_correo;
            $this->contacto_telefono = $this->cliente->contacto_telefono;
            $this->contacto_cargo = $this->cliente->contacto_cargo;
            $this->comentarios = $this->cliente->comentarios;
            $this->con_facturacion = $this->cliente->con_facturacion;
            $this->es_cliente_fiel = $this->cliente->es_cliente_fiel;
            $this->regimen_fiscal_id = $this->cliente->regimen_fiscal_id;
        }
        $this->direccion_fiscal = $this->cliente->direccion_fiscal->toArray();
        $this->estados = get_estados_mexico();
    }

    public static function modalMaxWidthClass(): string
    {
        return 'modal-xl'; // TODO: Change the autogenerated stub
    }

    public function render()
    {
        return view('livewire.clientes.save');
    }

    public function getWithScopeProperty()
    {
        return $this->scope != null;
    }

    public function hydrate()
    {
        $this->dispatchBrowserEvent('reApplySelect2');
        $this->init();
    }

    public function updated()
    {
        $this->dispatchBrowserEvent('reApplySelect2');
        $this->init();
    }

    public function updatedConstanciaFiscal($value)
    {
        if ($value) {
            if ($value->getMimeType() != 'application/pdf') {
                $this->emit('show-toast', 'Seleccione el fichero correcto. Solo se aceptan archivos del tipo PDF.', 'danger');
                return;
            }

            try {
                $parser = new Parser();
                $content = file_get_contents($value->getRealPath());
                $pdf = $parser->parseContent($content);
                $text = $pdf->getText();

                $datos_fiscales = extraer_datos_fiscales($text);

                if ($datos_fiscales['tipo_persona'] == 'fisica') {
                    $nombre = $datos_fiscales['nombre'] . ' ' . $datos_fiscales['apellido_paterno'] . ' ' . $datos_fiscales['apellido_materno'];
                    $this->razon_social = $nombre;
                    $this->nombre_comercial = $nombre;
                } else {
                    $this->razon_social = $datos_fiscales['razon_social'];
                    $this->nombre_comercial = $datos_fiscales['nombre_comercial'];
                }
                $this->rfc = $datos_fiscales['rfc'];
                $this->direccion_fiscal['codigo_postal'] = $datos_fiscales['codigo_postal'];
                $this->direccion_fiscal['calle'] = $datos_fiscales['calle'];
                $this->direccion_fiscal['no_exterior'] = $datos_fiscales['numero_exterior'];
                $this->direccion_fiscal['no_interior'] = $datos_fiscales['numero_interior'];
                $this->direccion_fiscal['colonia'] = $datos_fiscales['colonia'];
                $this->direccion_fiscal['ciudad'] = $datos_fiscales['localidad'];
                $this->direccion_fiscal['delegacion'] = $datos_fiscales['municipio'];
                $this->direccion_fiscal['estado'] = $datos_fiscales['estado'];
                $this->regimen_fiscal_id = optional(RegimenFiscal::findByDescription($datos_fiscales['regimen_fiscal']))->id;
                $this->direccion_fiscal['estado_id'] = Estado::where('nombre', $datos_fiscales['estado'])->first()?->id;
                if ($this->direccion_fiscal['estado_id']) {
                    $this->direccion_fiscal['localidad_id'] = Localidad::where('estado_id', $this->direccion_fiscal['estado_id'])->where('nombre', $datos_fiscales['localidad'])->first()?->id;
                    $this->direccion_fiscal['municipio_id'] = Municipio::where('estado_id', $this->direccion_fiscal['estado_id'])->where('nombre', $datos_fiscales['municipio'])->first()?->id;
                }
                $this->regimen_fiscal_id = optional(RegimenFiscal::findByDescription($datos_fiscales['regimen_fiscal']))->id;
                $this->emit('show-toast', 'Datos cargados correctamente.', 'success');
            } catch (Exception $e) {
                Log::error("cargando los datos fiscales desde documento fiscal. Error: {$e->getMessage()}");
                $this->emit('show-toast', 'Lo sentimos no se pudo realizar la carga de información. Documento inválido o corrupto.', 'danger');
            }
        }
    }

    public function rules()
    {
        $collection = DB::table('tb_clientes')
            ->select('id', 'nombre_comercial', 'razon_social', 'rfc', DB::raw('0 as decrypted'))
            ->where('es_cliente', 1)
            ->get();
        $collection->each(function ($cliente) {
            $cliente = Cliente::decryptInfo($cliente);
        });
        return [
            'nombre_comercial' => ['required', new RuleUnique($collection, $this->cliente->id)],
            'con_facturacion' => ['nullable', 'boolean'],
            'razon_social' => ['required_if:con_facturacion,true', new RuleUnique($collection, $this->cliente->id)],
            'rfc' => ['required_if:con_facturacion,true', new RuleUnique($collection, $this->cliente->id), new RfcRule('ambas')],
            'correo' => ['required', 'email'],
            'telefono' => ['nullable'],
            'contacto_nombre' => ['nullable'],
            'contacto_correo' => ['nullable', 'email'],
            'contacto_telefono' => ['nullable'],
            'contacto_cargo' => ['nullable'],
            'comentarios' => ['nullable'],
            'es_cliente_fiel' => 'nullable|boolean',
            'regimen_fiscal_id' => ['required_if:con_facturacion,true', new RfcYRegimenCoherentesRule($this->rfc)],
            'direccion_fiscal.codigo_postal' => ['required_if:con_facturacion,true'],
            'direccion_fiscal.calle' => 'nullable',
            'direccion_fiscal.no_exterior' => 'nullable',
            'direccion_fiscal.no_interior' => 'nullable',
            'direccion_fiscal.colonia' => 'nullable',
            'direccion_fiscal.localidad_id' => 'nullable',
            'direccion_fiscal.municipio_id' => 'nullable',
            'direccion_fiscal.estado_id' => 'nullable',
            'direccion_fiscal.referencia' => 'nullable'
        ];
    }

    public function messages()
    {
        return [
            'nombre_comercial.required' => 'Campo requerido',
            'razon_social.required_if' => 'Campo requerido',
            'rfc.required_if' => 'Campo requerido',
            'correo.required' => 'Campo requerido',
            'correo.email' => 'Formato incorrecto',
            'contacto_correo.email' => 'Formato incorrecto',
            'regimen_fiscal_id.required_if' => 'Campo requerido',
            'direccion_fiscal.codigo_postal.required_if' => 'Campo requerido.'
        ];
    }

    public function save()
    {
        $data = $this->validate(
            $this->rules(),
            // $this->messages()
        );

        DB::beginTransaction();
        try {

            $data['rfc'] = strtoupper(str_replace(' ', '', $data['rfc']));

            $clienteDB = $this->cliente->id ? null : Cliente::withTrashed()->where('rfc', $data['rfc'])->first();

            if (!$clienteDB)
                $clienteDB = $this->cliente;
            if ($clienteDB->trashed())
                $clienteDB->restore();

            $data['es_cliente'] = 1;
            $data = Cliente::encryptInfo($data);

            $data['regimen_fiscal_id'] = $data['regimen_fiscal_id'] ?: null;
            $clienteDB->fill(Arr::only($data, [
                'nombre_comercial',
                'razon_social',
                'rfc',
                'correo',
                'telefono',
                'contacto_nombre',
                'contacto_correo',
                'contacto_telefono',
                'contacto_cargo',
                'es_cliente',
                'es_cliente_fiel',
                'comentarios',
                'con_facturacion',
                'regimen_fiscal_id'
            ]))->save();

            if ($clienteDB->direccion_fiscal()->exists()) {
                $clienteDB->direccion_fiscal->fill([
                    'calle' => $data['direccion_fiscal']['calle'],
                    'no_exterior' => $data['direccion_fiscal']['no_exterior'],
                    'no_interior' => $data['direccion_fiscal']['no_interior'],
                    'codigo_postal' => $data['direccion_fiscal']['codigo_postal'],
                    'colonia' => $data['direccion_fiscal']['colonia'],
                    'localidad_id' => $data['direccion_fiscal']['localidad_id'] ? $data['direccion_fiscal']['localidad_id'] : null,
                    'municipio_id' => $data['direccion_fiscal']['municipio_id'] ? $data['direccion_fiscal']['municipio_id'] : null,
                    'estado_id' => $data['direccion_fiscal']['estado_id'] ? $data['direccion_fiscal']['estado_id'] : null,
                    'referencia' => $data['direccion_fiscal']['referencia'],
                ]);
                if (count($clienteDB->direccion_fiscal->getDirty()) > 0) {
                    $attributes = Arr::except($clienteDB->direccion_fiscal->getDirty(), ['created_at', 'updated_at']);
                    $log = $clienteDB->rfc ? "La Dirección Fiscal del Cliente con RFC: {$clienteDB->rfc}, ha sido actualizada." : "La Dirección Fiscal del Cliente con nombre comercial: {$this->cliente->nombre_comercial}, ha sido actualizada.";
                    activity('Dirección Fiscal de Cliente Actualizada')
                        ->on($clienteDB->direccion_fiscal)
                        ->event('updated')
                        ->withProperty('attributes', Direccion::parseData($attributes))
                        ->withProperty('old', Direccion::parseData(Arr::only($clienteDB->direccion_fiscal->getOriginal(), array_keys($attributes))))
                        ->log($log);
                    $clienteDB->direccion_fiscal->save();
                }
            } else {
                $dir = Direccion::create([
                    'calle' => $data['direccion_fiscal']['calle'],
                    'no_exterior' => $data['direccion_fiscal']['no_exterior'],
                    'no_interior' => $data['direccion_fiscal']['no_interior'],
                    'codigo_postal' => $data['direccion_fiscal']['codigo_postal'],
                    'colonia' => $data['direccion_fiscal']['colonia'],
                    'localidad_id' => $data['direccion_fiscal']['localidad_id'] ? $data['direccion_fiscal']['localidad_id'] : null,
                    'municipio_id' => $data['direccion_fiscal']['municipio_id'] ? $data['direccion_fiscal']['municipio_id'] : null,
                    'estado_id' => $data['direccion_fiscal']['estado_id'] ? $data['direccion_fiscal']['estado_id'] : null,
                    'referencia' => $data['direccion_fiscal']['referencia'],
                ]);
                $clienteDB->direccion_fiscal_id = $dir->id;
                $clienteDB->save();

                $log = $clienteDB->rfc ? "La Dirección Fiscal del Cliente con RFC: {$clienteDB->rfc}, ha sido creada." : "La Dirección Fiscal del Cliente con nombre comercial: {$clienteDB->nombre_comercial}, ha sido creada.";

                activity("Dirección Fiscal de Cliente Creada")
                    ->on($dir)
                    ->event('created')
                    ->withProperties(Direccion::parseData(Arr::except($dir->toArray(), ['updated_at'])))
                    ->log($log);
            }

            $this->emit('show-toast', 'Cliente guardado.');
            if ($this->scope) {
                if ($clienteDB->wasRecentlyCreated) {
                    $this->emitTo($this->scope, 'cliente-created', $clienteDB->id);
                } else {
                    $this->emitTo($this->scope, 'cliente-updated', $clienteDB->id);
                }
            } else {
                $this->emit('$refresh');
            }
            DB::commit();
            $this->emit('closeModal');
        } catch (\Exception $e) {
            DB::rollBack();
            Log::error($e->getMessage());
            $this->emit('show-toast', 'Ocurrio un error. ' . $e->getMessage(), 'danger');
        }
    }

    public function init()
    {
        if (user()->cannot($this->cliente->id ? 'updateCliente' : 'createCliente', $this->cliente->id ? $this->cliente : [Cliente::class])) {
            $this->emit('show-toast', 'No tiene permisos para realizar estar acción.', 'danger');
            $this->emit('closeModal');
            return;
        }

        if ($this->direccion_fiscal['estado_id']) {
            $estado = Estado::find($this->direccion_fiscal['estado_id']);
            $this->dispatchBrowserEvent("set-data-direccion_fiscal-estado_id", ['data' => [$estado->only('id', 'text')], 'term' => '', 'value' => $estado->id]);
        }
        if ($this->direccion_fiscal['localidad_id']) {
            $localidad = Localidad::find($this->direccion_fiscal['localidad_id']);
            $this->dispatchBrowserEvent("set-data-direccion_fiscal-localidad_id", ['data' => [$localidad->only('id', 'text')], 'term' => '', 'value' => $localidad->id]);
        }
        if ($this->direccion_fiscal['municipio_id']) {
            $municipio = Municipio::find($this->direccion_fiscal['municipio_id']);
            $this->dispatchBrowserEvent("set-data-direccion_fiscal-municipio_id", ['data' => [$municipio->only('id', 'text')], 'term' => '', 'value' => $municipio->id]);
        }
    }
}
