<?php

namespace App\Livewire\Facturas;

use App\Livewire\Layouts\Modal;
use App\Models\Factura;
use App\Models\Sucursal;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Crypt;

class PanelPac extends Modal
{
    public $sucursales =  [];

    protected $listeners = ['$refresh', 'changeTimbrado'];

    public static function modalMaxWidthClass(): string
    {
        return 'modal-lg'; // TODO: Change the autogenerated stub
    }

    public function mount()
    {
        $owner = get_owner();

        foreach ($owner->sucursales as $sucursal) {
            $sucursalArr = Sucursal::decryptInfo(Arr::only($sucursal->toArray(), ['id', 'nombre_comercial', 'razon_social', 'rfc', 'cfdi_timbrado_productivo', 'portal_pac']));
            $this->sucursales[] = $sucursalArr;
        }
    }

    public function render()
    {
        return view('livewire.facturas.panel-pac');
    }

    public function init()
    {
        if (user()->cannot('setPanelPac', [Factura::class])) {
            $this->dispatch('show-toast', __('site.common.client_no_permissions'), 'danger');
            return redirect()->to('/');
        }
    }

    public function changeTimbrado($index)
    {
        $sucursal = Sucursal::find($this->sucursales[$index]['id']);
        $sucursal->update(['cfdi_timbrado_productivo' => $this->sucursales[$index]['cfdi_timbrado_productivo']]);

        activity(__('site.panel_pac.log_updated'))
            ->on($sucursal)
            ->event('updated')
            ->withProperty('cfdi_timbrado_productivo', $this->sucursales[$index]['cfdi_timbrado_productivo'])
            ->log(__('site.panel_pac.log_updated_detail', ['nombre_comercial' => Crypt::decrypt($sucursal->nombre_comercial)]));

        $this->dispatch('show-toast', __('site.panel_pac.stamping_mode_changed'), 'success');
        $this->dispatch('$refresh');
    }
}
