<?php

namespace App\Livewire\Usuarios;

use App\Livewire\Layouts\Modal;
use App\Models\Cliente;
use App\Models\Sucursal;
use App\Models\User;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use Livewire\Component;

class ManagePermissionsSystem extends Modal
{
    public User $usuario;
    public $rolPermissionsGroup = [];
    public $othersPermissionsGroup = [];

    public function mount()
    {
        $userRolePermissions = $this->usuario->getPermissionsViaRoles()->pluck('name')->toArray();
        $userRolePermissionsGranted =  [];
        foreach ($userRolePermissions as $permission) {
            $key = explode('-', $permission)[0];
            if (!isset($this->rolPermissionsGroup[$key]))
                $this->rolPermissionsGroup[$key] = [];
            $this->rolPermissionsGroup[$key][] = $permission;
            $userRolePermissionsGranted[] = $permission;
        }

        $authUserPermissions = user()->getPermissionsViaRoles()->pluck('name')->toArray();
        $permissionsGranted  = $this->usuario->permissions()->pluck('name')->toArray();
        $othersPermissions = [];
        DB::table('permissions')
            ->select('name', DB::raw("0 as selected"))
            ->whereIn('name', $authUserPermissions)
            ->whereNotIn('name', $userRolePermissionsGranted)
            ->get()
            ->each(function ($element) use (&$othersPermissions, $permissionsGranted) {
                $othersPermissions[] = [
                    'name' => $element->name,
                    'selected' => in_array($element->name, $permissionsGranted)
                ];
            });

        foreach ($othersPermissions as $permission) {
            $key = explode('-', $permission['name'])[0];
            if (!isset($this->othersPermissionsGroup[$key]))
                $this->othersPermissionsGroup[$key] = [];
            $this->othersPermissionsGroup[$key][] = $permission;
        }
    }

    public function updated($field, $value)
    {
        if (Str::startsWith($field, 'othersPermissionsGroup.')) {
            $res = explode('.', $field);
            if ($value) {
                $this->usuario->givePermissionTo($this->othersPermissionsGroup[$res[1]][$res[2]]['name']);

                $this->dispatch('show-toast', __('site.users.manage_permissions.set_permission_success'));

                $log = __('site.users.manage_permissions.log_set_permission_success_detail', ['user' => $this->usuario->email]);
                activity(__('site.users.manage_permissions.log_set_permission_success'))
                    ->on($this->usuario)
                    ->event('updated')
                    ->withProperty('permiso', __('site.permissions.' . $this->othersPermissionsGroup[$res[1]][$res[2]]['name']))
                    ->withProperty('usuario', "{$this->usuario->nombre_completo} ({$this->usuario->email})")
                    ->log($log);
            } else {
                $this->usuario->revokePermissionTo($this->othersPermissionsGroup[$res[1]][$res[2]]['name']);

                $this->dispatch('show-toast', __('site.users.manage_permissions.revoke_permission_success'));

                $log = __('site.users.manage_permissions.log_revoke_permission_success_detail', ['user' => $this->usuario->email]);
                activity(__('site.users.manage_permissions.log_revoke_permission_success'))
                    ->on($this->role)
                    ->event('updated')
                    ->withProperty('permiso', __('site.permissions.' . $this->othersPermissionsGroup[$res[1]][$res[2]]['name']))
                    ->withProperty('usuario', "{$this->usuario->nombre_completo} ({$this->usuario->email})")
                    ->log($log);
            }
        }
    }

    public function getRolProperty()
    {
        $roles = [];
        foreach ($this->usuario->getRoleNames()->toArray() as $r)
            $roles[] = __('site.roles.values.' . $r);

        return Str::replaceLast(', ', ' ' . __('site.common.and') . ' ',  implode(', ', $roles));
    }

    public static function modalMaxWidthClass(): string
    {
        return ''; // TODO: Change the autogenerated stub
    }

    public function render()
    {
        return view('livewire.usuarios.manage-permissions-system');
    }

    public function init()
    {
        if (user()->cannot('users-assignPermissions', $this->usuario)) {
            $this->dispatch('show-toast', __('site.common.client_no_permissions'), 'danger');
            $this->dispatch('closeModal');
            return;
        }
    }
}
