<?php

namespace App\Livewire\Usuarios;

use App\Livewire\Layouts\Modal;
use App\Models\Cliente;
use App\Models\Sucursal;
use App\Models\User;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use Livewire\Component;

class SetBranches extends Modal
{
    public User $usuario;
    public $sucursales = [];

    public function mount()
    {
        $sucursalesUsuario = $this->usuario->sucursales()->pluck('id')->toArray();

        Sucursal::where('cliente_id', $this->usuario->cliente_id)
            ->whereHas('suscripcion', function ($query) {
                $query->where('estado', 'ACTIVA');
            })
            ->select('id', 'nombre_comercial', 'suscripcion_id', 'cliente_id', DB::raw("0 as seleccionada"))
            ->get()
            ->each(function ($element) use ($sucursalesUsuario) {
                $this->sucursales[] = [
                    'id' => $element->id,
                    'suscripcion_id' => $element->suscripcion_id,
                    'nombre_comercial' => Crypt::decrypt($element->nombre_comercial),
                    'cliente' => Cliente::find($element->cliente_id)->nombre_comercial,
                    'seleccionada' => in_array($element->id, $sucursalesUsuario)
                ];
            });
    }

    public function updated($field, $value)
    {
        if (Str::startsWith($field, 'sucursales.')) {
            $res = explode('.', $field);
            if ($res[2] == 'seleccionada') {
                if ($value) {
                    $this->usuario->sucursales()->attach($this->sucursales[$res[1]]['id']);
                    $this->usuario->suscripciones()->syncWithoutDetaching($this->sucursales[$res[1]]['suscripcion_id']);

                    $this->dispatch('show-toast', __('site.users.set_branches.set_branch_success'));

                    $log = __('site.users.set_branches.log_set_branch_success_detail', ['user' => $this->usuario->email]);
                    activity(__('site.users.set_branches.log_set_branch_success'))
                        ->on($this->usuario)
                        ->event('updated')
                        ->withProperty('usuario', "{$this->usuario->nombre_completo} ({$this->usuario->email})")
                        ->withProperty('sucursal', Crypt::encrypt($this->sucursales[$res[1]]['nombre_comercial']))
                        ->withProperty('cliente', $this->sucursales[$res[1]]['cliente'])
                        ->log($log);
                } else {
                    $this->usuario->sucursales()->detach($this->sucursales[$res[1]]['id']);
                    if ($this->usuario->sucursales()->where('suscripcion_id', $this->sucursales[$res[1]]['suscripcion_id'])->count() == 0)
                        $this->usuario->suscripciones()->detach($this->sucursales[$res[1]]['suscripcion_id']);

                    $this->dispatch('show-toast', __('site.users.set_branches.remove_branch_success'));

                    $log = __('site.users.set_branches.log_remove_branch_success_detail', ['user' => $this->usuario->email]);
                    activity(__('site.users.set_branches.log_remove_branch_success'))
                        ->on($this->usuario)
                        ->event('updated')
                        ->withProperty('usuario', "{$this->usuario->nombre_completo} ({$this->usuario->email})")
                        ->withProperty('sucursal', Crypt::encrypt($this->sucursales[$res[1]]['nombre_comercial']))
                        ->withProperty('cliente', $this->sucursales[$res[1]]['cliente'])
                        ->log($log);
                }
            }
        }
    }

    public static function modalMaxWidthClass(): string
    {
        return 'modal-lg'; // TODO: Change the autogenerated stub
    }

    public function render()
    {
        return view('livewire.usuarios.set-branches');
    }

    public function init()
    {
        if (user()->cannot('setBranches', $this->usuario)) {
            $this->dispatch('show-toast', __('site.common.client_no_permissions'), 'danger');
            $this->dispatch('closeModal');
            return;
        }
    }

    public function restore()
    {
        $this->usuario = User::withTrashed()->find($this->usuario);
        $this->usuario->restore();

        activity(__('site.users.restore.log_restored'))
            ->on($this->usuario)
            ->event('restored')
            ->withProperties(User::parseData($this->usuario->getAttributes()))
            ->log(__('site.users.restore.log_restored_detail',  ['email' => $this->usuario->email]));

        $this->dispatch('show-toast', __('site.users.restore.user_activated'));
        $this->dispatch('$refresh');
        $this->dispatch('closeModal');
    }
}
