<?php

namespace App\Http\Livewire;

use App\Http\Livewire\Layouts\Modal;
use App\Models\Factura;
use App\Models\Sucursal;
use Illuminate\Support\Arr;

class PanelPac extends Modal
{
    public $sucursales =  [];

    protected $listeners = ['$refresh', 'changeTimbrado'];

    public static function modalMaxWidthClass(): string
    {
        return 'modal-md'; // TODO: Change the autogenerated stub
    }

    public function mount()
    {
        $owner = get_owner();

        foreach ($owner->sucursales as $sucursal) {
            $sucursalArr = Sucursal::decryptInfo(Arr::only($sucursal->toArray(), ['id', 'nombre_comercial', 'razon_social', 'rfc', 'cfdi_timbrado_productivo', 'portal_pac']));
            $this->sucursales[] = $sucursalArr;
        }
    }

    public function render()
    {
        return view('livewire.panel-pac');
    }

    public function init()
    {
        if (user()->cannot('setPanelPac', [Factura::class])) {
            $this->emit('show-toast', 'No tiene permisos para realizar estar acción.', 'danger');
            return redirect()->to('/');
        }
    }

    public function changeTimbrado($index)
    {
        Sucursal::where('id', $this->sucursales[$index]['id'])->update(['cfdi_timbrado_productivo' => $this->sucursales[$index]['cfdi_timbrado_productivo']]);
        $this->emit('show-toast', 'Modo de Timbrado cambiado.');
        $this->emit('$refresh');
    }
}
