<?php

namespace App\Http\Livewire;

use App\Http\Livewire\Layouts\Modal;

class PanelPac extends Modal
{
    public $cfdi_timbrado_productivo;
    public $owner;

    protected $listeners = ['$refresh'];

    public static function modalMaxWidthClass(): string
    {
        return 'modal-md'; // TODO: Change the autogenerated stub
    }

    public function mount()
    {
        $this->owner = get_owner()->toArray();
        $this->cfdi_timbrado_productivo = system_config('cfdi_timbrado_productivo');
    }

    public function render()
    {
        return view('livewire.panel-pac');
    }

    public function changeTimbrado()
    {
        system_config('cfdi_timbrado_productivo', $this->cfdi_timbrado_productivo);
        $this->emit('show-toast', 'Modo de Timbrado cambiado.');
        $this->emit('$refresh');
    }
}
