<?php

namespace App\Http\Livewire\CuentasCobrar;

use App\Http\Livewire\Layouts\Modal;
use App\Models\Factura;

class DetallesPagoFactura extends Modal
{
    public $scope;
    public Factura $factura;
    public $pagos = [];

    protected $listeners = ['$refresh'];

    public function mount()
    {
        $this->pagos = $this->factura->ingresos()->get()->map(function($element){
            return[
                'fecha_str' => $element->fecha->format('d/m/Y'),
                'monto' => $element->pivot->monto,
                'moneda' => $element->pivot->moneda
            ];
        })->toArray();
    }

    public static function modalMaxWidthClass(): string
    {
        return 'modal-md'; // TODO: Change the autogenerated stub
    }

    public function getTipoProperty(){
        if($this->factura->es_nota_venta){
            return 'Nota de Venta';
        }
        return 'Factura';
    }
    public function render()
    {
        return view('livewire.cuentas-cobrar.detalles-pago-factura');
    }
}
