<?php

namespace App\Http\Livewire\CuentasCobrar;

use App\Http\Livewire\Layouts\Modal;
use App\Models\Cliente;
use App\Models\Factura;
use App\Models\Ingreso;
use App\Rules\IngresoNotaCreditoRule;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;

class Ingresar extends Modal
{
    public $scope;
    public $facturas_ids = '';
    public $facturas = [];
    public $fecha = null;
    public $comentarios = null;

    public $total_nota_credito = '';

    public $con_nota_credito = false;
    public $con_diferente_moneda = false;

    public $monedas = ['MXN', 'USD'];

    protected $listeners = ['$refresh', 'updatedNotaCredito', 'close'];

    public function mount()
    {
        $this->fecha = today()->format('Y-m-d');
        $this->facturas = DB::table('tb_facturas as factura')
            ->select(
                'factura.id',
                'factura.cliente_id',
                DB::raw("(factura.total - IFNULL((SELECT SUM(ing_f.monto_moneda_original + IFNULL(nc.total, 0)) from tb_ingresos_facturas as ing_f left join tb_facturas as nc on nc.id = ing_f.nota_credito_id where ing_f.factura_id = factura.id), 0)) as pendiente_ingresar"),
                DB::raw("(factura.total - IFNULL((SELECT SUM(ing_f.monto_moneda_original + IFNULL(nc.total, 0)) from tb_ingresos_facturas as ing_f left join tb_facturas as nc on nc.id = ing_f.nota_credito_id where ing_f.factura_id = factura.id), 0)) as limite"),
                DB::raw("(factura.total - IFNULL((SELECT SUM(ing_f.monto_moneda_original + IFNULL(nc.total, 0)) from tb_ingresos_facturas as ing_f left join tb_facturas as nc on nc.id = ing_f.nota_credito_id where ing_f.factura_id = factura.id), 0)) as monto_moneda_original"),
                DB::raw("(factura.total - IFNULL((SELECT SUM(ing_f.monto_moneda_original + IFNULL(nc.total, 0)) from tb_ingresos_facturas as ing_f left join tb_facturas as nc on nc.id = ing_f.nota_credito_id where ing_f.factura_id = factura.id), 0)) as monto"),
                DB::raw("null as nota_credito_id"),
                DB::raw("0 as total_nota_credito"),
                DB::raw("'' as notasCredito"),
                'factura.moneda',
                'factura.moneda as moneda_referencia'
                // DB::raw("1 as tipo_cambio")
            )
            ->whereIn('id', explode(',', Str::replaceLast(',', '', $this->facturas_ids)))
            ->get()->map(function ($element) {
                return (array)$element;
            })->toArray();

        foreach ($this->facturas as $index => $factura) {
            $this->facturas[$index]['notasCredito'] = DB::table('tb_facturas')
                ->select(
                    'id as value',
                    DB::raw("IFNULL(folio_interno, 'S/F') as label"),
                    'moneda',
                    'total'
                )
                ->where('cliente_id', $factura['cliente_id'])
                ->where('es_nota_credito', 1)
                ->whereRaw("(SELECT COUNT(id) from tb_ingresos_facturas where nota_credito_id = tb_facturas.id) = 0")
                ->get()
                ->map(function ($item) {
                    return (array) $item;
                })
                ->toArray();
        }
    }

    public function updatedNotaCredito($index)
    {
        if ($this->facturas[$index]['nota_credito_id']) {
            $this->facturas[$index]['total_nota_credito'] = DB::table('tb_facturas')->select('total')->where('id', $this->facturas[$index]['nota_credito_id'])->first()->total;
            $this->facturas[$index]['limite'] = $this->facturas[$index]['pendiente_ingresar'] - $this->facturas[$index]['total_nota_credito'];
            $this->facturas[$index]['monto_moneda_original'] = $this->facturas[$index]['pendiente_ingresar'] - $this->facturas[$index]['total_nota_credito'];
            $this->facturas[$index]['monto'] = $this->facturas[$index]['pendiente_ingresar'] - $this->facturas[$index]['total_nota_credito'];
        } else {
            $this->facturas[$index]['total_nota_credito'] = 0;
            $this->facturas[$index]['limite'] = $this->facturas[$index]['pendiente_ingresar'];
            $this->facturas[$index]['monto_moneda_original'] = $this->facturas[$index]['pendiente_ingresar'];
            $this->facturas[$index]['monto'] = $this->facturas[$index]['pendiente_ingresar'];
        }
    }

    public static function modalMaxWidthClass(): string
    {
        return 'modal-lg'; // TODO: Change the autogenerated stub
    }

    public function getConNotasCreditoProperty()
    {
        return count($this->notasCredito) > 0;
    }

    public function getMontoLimiteProperty()
    {
        return $this->factura->total - $this->factura->monto_ingresado + 0.01;
    }

    public function getTotalesProperty()
    {
        $total_mxn = 0;
        $total_usd = 0;

        foreach ($this->facturas as $factura) {
            if ($factura['moneda'] == 'USD')
                $total_usd += $factura['monto'];
            if ($factura['moneda'] == 'MXN')
                $total_mxn += $factura['monto'];
        }

        return [
            'total_usd' => $total_usd,
            'total_mxn' => $total_mxn
        ];
    }

    public function render()
    {
        return view('livewire.cuentas-cobrar.ingresar');
    }

    public function save()
    {
        $rules = [
            'fecha' => ['required', 'date'],
            'comentarios' => ['nullable'],
            'facturas' => ['array', 'required', 'min:1'],
            'facturas.*.id' => ['required', 'exists:tb_facturas,id'],
            'facturas.*.limite' => ['numeric', 'nullable'],
            'facturas.*.pendiente_ingresar' => ['numeric', 'nullable'],
            'facturas.*.moneda' => ['required', Rule::in(['MXN', 'USD'])],
            'facturas.*.moneda_referencia' => ['nullable'],
            // 'facturas.*.tipo_cambio' => ['required', 'numeric', 'min:1'],
            'facturas.*.nota_credito_id' => 'nullable',
        ];
        $messages = [
            'fecha.required' => 'Campo requerido.',
            'facturas.*.id.required' => 'Factura no seleccionada.',
            'facturas.*.id.exists' => 'Factura no encontrada.',
            'facturas.*.moneda.required' => 'Campo requerido.',
            'facturas.*.moneda.in' => 'Moneda inválida.',
            // 'facturas.*.tipo_cambio.required' => 'Campo requerido.',
            // 'facturas.*.tipo_cambio.min' => 'Entre un valor superior.',
        ];

        foreach ($this->facturas as $index => $factura) {
            if ($factura['moneda'] != $factura['moneda_referencia']) {
                // $factura['limite'] = $factura['moneda_referencia'] == 'USD' ? round($factura['pendiente_ingresar'] * $factura['tipo_cambio'], 2) : round($factura['pendiente_ingresar'] / $factura['tipo_cambio'], 2);
                $rules["facturas.$index.monto_moneda_original"] = ['numeric', 'required', 'min:1', new IngresoNotaCreditoRule($factura)];
                $rules["facturas.$index.monto"] = ['numeric', 'required', 'min:1'];
                $messages["facturas.$index.monto_moneda_original.required"] = "Campo requerido!";
                $messages["facturas.$index.monto_moneda_original.min"] = "Entre un valor mayor!";
            } else {
                $rules["facturas.$index.monto"] = ['numeric', 'required', 'min:1', new IngresoNotaCreditoRule($factura)];
            }

            $messages["facturas.$index.monto.required"] = "Campo requerido!";
            $messages["facturas.$index.monto.min"] = "Entre un valor mayor!";
        }

        $data = $this->validate(
            $rules,
            // $messages
        );

        DB::beginTransaction();

        $ingreso = Ingreso::create([
            'fecha' => $data['fecha'],
            'comentarios' => $data['comentarios']
        ]);

        foreach ($data['facturas'] as $factura) {
            $monto = (float)$factura['monto'];

            if ($factura['moneda'] == $factura['moneda_referencia']) {
                // $monto = $factura['moneda_referencia'] == 'USD' ? round($factura['monto'] * $factura['tipo_cambio'], 2) : round($factura['monto'] / $factura['tipo_cambio'], 2);
                $factura['monto_moneda_original'] = $monto;
            }

            $ingreso->facturas()->syncWithPivotValues($factura['id'], [
                'nota_credito_id' => $factura['nota_credito_id'],
                'monto' => $factura['monto'],
                'monto_moneda_original' => $factura['monto_moneda_original'],
                // 'tipo_cambio' => $factura['tipo_cambio'],
                'moneda' => $factura['moneda']
            ], false);
            $f = Factura::find($factura['id']);

            $cliente = Cliente::find($f->cliente_id);

            if ($cliente->requiere_complemento) {

                if (!get_tipo_cambio_sistema()->id) {
                    $this->emit('show-toast', 'Debe definir el Tipo de Cambio para hoy!', 'danger');
                    DB::rollBack();
                    return;
                }

                $complemento = new Factura();
                $complemento->estado = 'CAPTURADA';
                $complemento->es_complemento = 1;
                $complemento->fecha_emision = now();
                $complemento->fecha_pago = now();
                $complemento->porciento_iva = system_iva();
                $complemento->lugar_expedicion = optional(get_system_owner()->direccion_fiscal)->codigo_postal;
                $complemento->moneda = $f->moneda;
                $complemento->tipo_comprobante_id = 5;
                $complemento->propietario_id = get_system_owner()->id;
                $complemento->cliente_id = $f->cliente_id;
                $complemento->cfdi_id = 6;
                $complemento->serie_id = 4;
                $complemento->forma_pago_id = 1;
                $complemento->tipo_cambio = get_tipo_cambio_sistema()->tasa;

                $balance_previo = $factura['nota_credito_id'] ? $factura['total_nota_credito'] : $factura['monto_moneda_original'];
                $total = $factura['nota_credito_id'] ? $factura['monto'] : $factura['monto_moneda_original'];

                $numero_parcialidad = 1;
                $complementos = DB::table('tb_facturas_complementos as f_c')
                    ->select('f_c.importe_pagado')
                    ->join('tb_facturas as c', 'f_c.complemento_id', '=', 'c.id')
                    ->where('f_c.factura_id', $f->id)
                    ->whereNotIn('c.estado', ['CANCELADA'])
                    ->get();
                $complementos->map(function ($comp) use (&$total) {
                    $total -= (float)$comp->importe_pagado;
                });
                $numero_parcialidad += $complementos->count();

                $complemento->total = $total;
                $complemento->subtotal = round($total / (1 + system_iva()), 2);
                $complemento->iva = $total - $complemento->subtotal;
                $complemento->cantidad_letras = convertir_numero_a_letras($total, $complemento->moneda);
                $complemento->save();

                $complemento->facturas()->syncWithPivotValues($f, [
                    'no_parcialidad' => $numero_parcialidad,
                    'balance_previo' => $balance_previo,
                    'importe_pagado' => $total
                ]);
            }

            if ($f->pendiente_ingresar < 0.01) {
                DB::table('tb_facturas')->where('id', $f->id)->update(['estado' => 'COBRADA']);
            }
        }

        DB::commit();
        $this->emit('show-toast', "Ingreso registrado satisfactoriamente.");
        $this->emit('closeModal');
        return redirect()->route('cuentas_cobrar.index');
    }

    public function close()
    {
        $this->emit('closeModal');
    }
}
