<?php

namespace App\Livewire\Roles;

use App\Livewire\Layouts\Modal;
use App\Models\Modulo;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class ManagePermissions extends Modal
{
    public Role $role;
    public $permissionsGroups = [];
    public function mount()
    {
        $rolPermissions = user()->cliente->rolePermissions($this->role->id)->pluck('name')->toArray();
        $authUserPermissions = user()->getPermissionsViaRoles()->pluck('name')->toArray();

        $permissions = [];
        DB::table('permissions')
            ->select('name', DB::raw("0 as selected"))
            ->whereIn('name', $authUserPermissions)
            ->get()
            ->each(function ($element) use (&$permissions, $rolPermissions) {
                $permissions[] = [
                    'name' => $element->name,
                    'selected' => in_array($element->name, $rolPermissions)
                ];
            });

        foreach ($permissions as $permission) {
            $key = explode('-', $permission['name'])[0];
            if (!isset($this->permissionsGroups[$key]))
                $this->permissionsGroups[$key] = [];
            $this->permissionsGroups[$key][] = $permission;
        }
    }

    public static function modalMaxWidthClass(): string
    {
        return 'modal-xl'; // TODO: Change the autogenerated stub
    }

    public function updated($field, $value)
    {
        if (Str::startsWith($field, 'permissionsGroups.')) {
            $res = explode('.', $field);
            $permission = Permission::findByName($this->permissionsGroups[$res[1]][$res[2]]['name']);
            if ($value) {
                user()->cliente->roles_permissions()->attach($permission->id, ['role_id' => $this->role->id]);

                $users = User::where('cliente_id', user()->cliente_id)->get();
                foreach ($users as $u) {
                    if ($u->hasRole($this->role->name) && !$u->hasPermissionTo($permission->name)) {
                        $u->givePermissionTo($permission->name);
                    }
                }

                $this->dispatch('show-toast', __('site.roles.manage_permissions.set_permission_success'));

                $log = __('site.roles.manage_permissions.log_set_permission_success_detail', ['rol' => __('site.roles.values.' . $this->role->name)]);
                activity(__('site.roles.manage_permissions.log_set_permission_success'))
                    ->on($this->role)
                    ->event('updated')
                    ->withProperty('permiso', __('site.permissions.' . $this->permissionsGroups[$res[1]][$res[2]]['name']))
                    ->withProperty('rol', __('site.roles.values.' . $this->role->name))
                    ->withProperty('cliente', user()->cliente->nombre_comercial)
                    ->log($log);
            } else {
                user()->cliente->roles_permissions()->detach($permission->id);

                $this->dispatch('show-toast', __('site.roles.manage_permissions.revoke_permission_success'));

                $users = User::where('cliente_id', user()->cliente_id)->get();
                foreach ($users as $u) {
                    if ($u->hasRole($this->role->name) && $u->hasPermissionTo($permission->name)) {
                        $u->revokePermissionTo($permission->name);
                    }
                }

                $log = __('site.roles.manage_permissions.log_revoke_permission_success_detail', ['rol' => __('site.roles.values.' . $this->role->name)]);
                activity(__('site.roles.manage_permissions.log_revoke_permission_success'))
                    ->on($this->role)
                    ->event('updated')
                    ->withProperty('permiso', __('site.permissions.' . $this->permissionsGroups[$res[1]][$res[2]]['name']))
                    ->withProperty('rol', __('site.roles.values.' . $this->role->name))
                    ->withProperty('cliente', user()->cliente->nombre_comercial)
                    ->log($log);
            }
        }
    }

    public function render()
    {
        return view('livewire.roles.manage-permissions');
    }

    public function init()
    {
        if (user()->cannot('roles-assignPermissions') && in_array($this->role->name, ['Manager'])) {
            $this->dispatch('show-toast', __('site.common.client_no_permissions'), 'danger');
            $this->dispatch('closeModal');
            return;
        }
    }
}
