<?php

namespace App\Http\Livewire\Terminales;

use App\Http\Livewire\Layouts\Modal;
use App\Models\Sucursal;
use App\Models\Suscripcion;
use App\Models\Terminal;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class Save extends Modal
{
    public $scope = null;

    public Terminal $terminal;
    public $nombre;
    public $identificador;
    public $es_vk;
    public $comentarios;
    public $sucursal_id;
    public $cliente_id;
    public $suscripcion_id;
    protected $listeners = ['$refresh'];

    public function mount()
    {
        $this->nombre = isset($this->terminal) ? $this->terminal->nombre : '';
        $this->identificador = isset($this->terminal) ? $this->terminal->identificador : str_shuffle(uniqid());
        $this->es_vk = isset($this->terminal) ? $this->terminal->es_vk : false;
        $this->comentarios = isset($this->terminal) ? $this->terminal->comentarios : '';
        if (!isset($this->terminal)) {
            $this->terminal = new Terminal();
        }
    }

    public function hydrate()
    {
        $this->dispatchBrowserEvent('reApplySelect2');
    }

    public static function modalMaxWidthClass(): string
    {
        return 'modal-md'; // TODO: Change the autogenerated stub
    }
    public function render()
    {
        return view('livewire.terminales.save');
    }

    public function init()
    {
        if (user()->cannot($this->terminal->exists() ? 'update' : 'create', $this->terminal->exists() ? $this->terminal : [Terminal::class])) {
            $this->emit('show-toast', __('site.common.client_no_permissions'), 'danger');
            $this->emit('closeModal');
            return;
        }
    }

    public function save()
    {
        $data = $this->validate(
            [
                'nombre' => ['required'],
                'identificador' => ['required'],
                'es_vk' => ['nullable','boolean'],
                'comentarios' => ['nullable'],
            ],
            // $messages
        );

        $this->terminal->fill($data)->save();

        $this->emit('show-toast', __('site.terminals.save.terminal_saved'));
        $this->emit('$refresh');
        $this->emit('closeModal');
    }
}
