<?php

namespace App\Http\Livewire\Terminales;

use App\Http\Livewire\Layouts\Modal;
use App\Models\Sucursal;
use App\Models\Suscripcion;
use App\Models\Terminal;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class SaveSystem extends Modal
{
    public $scope = null;

    public Terminal $terminal;
    public $nombre;
    public $identificador;
    public $comentarios;
    public $sucursal_id;
    public $cliente_id;
    public $suscripcion_id;

    public $sucursales = [];
    public $suscripciones = [];
    public $clientes = [];
    public $from_subscription = false;
    protected $listeners = ['$refresh'];

    public function mount()
    {
        $this->nombre = isset($this->terminal) ? $this->terminal->nombre : '';
        $this->identificador = isset($this->terminal) ? $this->terminal->identificador : str_shuffle(uniqid());
        $this->comentarios = isset($this->terminal) ? $this->terminal->comentarios : '';
        $this->suscripcion_id = isset($this->terminal) ? $this->terminal->suscripcion_id : '';
        if (!$this->sucursal_id)
            $this->sucursal_id = isset($this->terminal) ? $this->terminal->sucursal_id : '';
        if ($this->sucursal_id)
            $this->cliente_id = Sucursal::find($this->sucursal_id)->cliente_id;

        if (!isset($this->terminal)) {
            $this->terminal = new Terminal();
        }

        $this->clientes = DB::table('tb_clientes')
            ->select('id as value', 'nombre_comercial as label')
            ->where('es_cliente', 1)
            ->where('deleted_at', null)
            ->get()->map(function ($element) {
                $element->label = Crypt::decrypt($element->label);
                return (array) $element;
            })->toArray();

        if ($this->cliente_id) {
            $this->sucursales = DB::table('tb_sucursales')
                ->select('id as value', 'nombre_comercial as label')
                ->where('deleted_at', null)
                ->where('cliente_id', $this->cliente_id)
                ->get()->map(function ($element) {
                    $element->label = Crypt::decrypt($element->label);
                    return (array) $element;
                })->toArray();
            $this->loadSuscripciones();
        }
    }

    public function hydrate()
    {
        $this->dispatchBrowserEvent('reApplySelect2');
    }

    public static function modalMaxWidthClass(): string
    {
        return 'modal-md'; // TODO: Change the autogenerated stub
    }

    public function updatedClienteId($value)
    {
        $this->sucursal_id = null;
        $this->sucursales = [];
        $this->suscripcion_id = null;
        $this->suscripciones = [];
        if ($value) {
            $this->sucursales = DB::table('tb_sucursales')
                ->select('id as value', 'nombre_comercial as label')
                ->where('deleted_at', null)
                ->where('cliente_id', $value)
                ->get()->map(function ($element) {
                    $element->label = Crypt::decrypt($element->label);
                    return (array) $element;
                })->toArray();

            $this->loadSuscripciones();
        }
    }

    public function getWithScopeProperty()
    {
        return $this->scope != null;
    }

    public function render()
    {
        return view('livewire.terminales.save-system');
    }

    public function init()
    {
        if (user()->cannot($this->terminal->exists() ? 'update' : 'create', $this->terminal->exists() ? $this->terminal : [Terminal::class])) {
            $this->emit('show-toast', __('site.common.client_no_permissions'), 'danger');
            $this->emit('closeModal');
            return;
        }
    }

    public function save()
    {
        $rules = $this->terminal->rules();
        $messages = $this->terminal->messages();
        $data = $this->validate(
            $rules,
            // $messages
        );

        if (!$this->terminal->exists())
            while (DB::table(table: 'tb_terminales')->where('identificador', $data['identificador'])->count() > 0) {
                $data['identificador'] = str_shuffle(uniqid());
            }

        $this->terminal->fill($data)->save();

        $this->emit('show-toast', __('site.terminals.save.terminal_saved'));

        if ($this->scope) {
            if ($this->terminal->wasRecentlyCreated) {
                $this->emitTo($this->scope, 'terminal-created', $this->terminal->id);
            } else {
                $this->emitTo($this->scope, 'terminal-updated', $this->terminal->id);
            }
        } else {
            $this->emit('$refresh');
        }
        $this->emit('closeModal');
    }

    public function loadSuscripciones()
    {
        Suscripcion::where('estado', 'ACTIVA')->where('cliente_id', $this->cliente_id)->withCount('terminales')->each(function (Suscripcion $suscripcion) {
            if (
                $suscripcion->terminales_count < $suscripcion->cant_terminales
                || $suscripcion->id == $this->suscripcion_id
            ) {
                $this->suscripciones[] = $suscripcion->only(['value', 'label']);
            }
        });
    }
}
