<?php

namespace App\Livewire\Auth;

use App\Livewire\Layouts\Modal;
use App\Models\RegimenFiscal;
use App\Models\Direccion;
use App\Models\Estado;
use App\Models\Localidad;
use App\Models\Municipio;
use App\Models\Cliente;
use App\Rules\RfcRule;
use App\Rules\RfcYRegimenCoherentesRule;
use App\Rules\RuleUnique;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Livewire\WithFileUploads;

class MyCompany extends Modal
{
    use WithFileUploads;
    public $scope = null;
    public Cliente $company;
    public $nombre_comercial;
    public $razon_social;
    public $rfc;
    public $correo;
    public $telefono;
    public $comentarios;
    public $con_facturacion;
    public $regimen_fiscal_id;
    public $direccion_fiscal;
    public $logo;
    public $logo_src;

    public $regimenesFiscales = [];
    public $estados = [];
    protected $listeners = ['$refresh'];

    public function mount()
    {
        $this->company = user()->cliente ?? get_system_owner();
        $this->regimenesFiscales = RegimenFiscal::orderBy('codigo')->get()->map->only(['label', 'value']);

        $this->company = Cliente::decryptInfo($this->company);
        $this->nombre_comercial = $this->company->nombre_comercial;
        $this->razon_social = $this->company->razon_social;
        $this->rfc = $this->company->rfc;
        $this->correo = $this->company->correo;
        $this->telefono = $this->company->telefono;
        $this->comentarios = $this->company->comentarios;
        $this->con_facturacion = $this->company->con_facturacion;
        $this->regimen_fiscal_id = $this->company->regimen_fiscal_id;
        $this->direccion_fiscal = $this->company->direccion_fiscal->toArray();
        $this->estados = get_estados_mexico();

        $this->logo_src = $this->company->logo_uri;
    }

    public static function modalMaxWidthClass(): string
    {
        return 'modal-xl'; // TODO: Change the autogenerated stub
    }

    public function render()
    {
        return view('livewire.auth.my-company');
    }

    public function getWithScopeProperty()
    {
        return $this->scope != null;
    }

    public function hydrate()
    {
        $this->dispatch('reApplySelect2');
        $this->init();
    }

    public function updated()
    {
        $this->dispatch('reApplySelect2');
        $this->init();
    }

    public function rules()
    {
        $collection = DB::table('tb_clientes')
            ->select('id', 'nombre_comercial', 'razon_social', 'rfc', DB::raw('0 as decrypted'))
            ->get();
        $collection->each(function ($cliente) {
            $cliente = Cliente::decryptInfo($cliente);
        });
        return [
            'nombre_comercial' => ['required', new RuleUnique($collection, $this->company->id)],
            'con_facturacion' => ['nullable', 'boolean'],
            'razon_social' => ['required_if:con_facturacion,true', new RuleUnique($collection, $this->company->id)],
            'rfc' => ['required_if:con_facturacion,true', new RuleUnique($collection, $this->company->id), new RfcRule('ambas')],
            'correo' => ['required'],
            'telefono' => ['nullable'],
            'comentarios' => ['nullable'],
            'regimen_fiscal_id' => ['required_if:con_facturacion,true', new RfcYRegimenCoherentesRule($this->rfc)],
            'direccion_fiscal.codigo_postal' => ['required_if:con_facturacion,true'],
            'direccion_fiscal.calle' => 'nullable',
            'direccion_fiscal.no_exterior' => 'nullable',
            'direccion_fiscal.no_interior' => 'nullable',
            'direccion_fiscal.colonia' => 'nullable',
            'direccion_fiscal.localidad_id' => 'nullable',
            'direccion_fiscal.municipio_id' => 'nullable',
            'direccion_fiscal.estado_id' => 'nullable',
            'direccion_fiscal.referencia' => 'nullable'
        ];
    }

    public function messages()
    {
        return [
            'nombre_comercial.required' => 'Campo requerido',
            'razon_social.required_if' => 'Campo requerido',
            'rfc.required_if' => 'Campo requerido',
            'correo.required' => 'Campo requerido',
            'regimen_fiscal_id.required_if' => 'Campo requerido',
            'direccion_fiscal.codigo_postal.required_if' => 'Campo requerido.'
        ];
    }

    public function save()
    {
        if (user()->cannot('myCompany-update')) {
            $this->dispatch('show-toast', __('site.common.client_no_permissions'), 'danger');
            $this->dispatch('closeModal');
            return;
        }

        $data = $this->validate(
            $this->rules(),
            // $this->messages()
        );
        DB::beginTransaction();
        try {
            $data['rfc'] = strtoupper(str_replace(' ', '', $data['rfc']));
            $data = Cliente::encryptInfo($data);

            $this->company->fill(Arr::only($data, [
                'nombre_comercial',
                'razon_social',
                'rfc',
                'correo',
                'telefono',
                'comentarios',
                'con_facturacion',
                'regimen_fiscal_id',
            ]))->save();

            if ($this->company->direccion_fiscal()->exists()) {
                $this->company->direccion_fiscal->fill([
                    'calle' => $data['direccion_fiscal']['calle'],
                    'no_exterior' => $data['direccion_fiscal']['no_exterior'],
                    'no_interior' => $data['direccion_fiscal']['no_interior'],
                    'codigo_postal' => $data['direccion_fiscal']['codigo_postal'],
                    'colonia' => $data['direccion_fiscal']['colonia'],
                    'localidad_id' => $data['direccion_fiscal']['localidad_id'] ? $data['direccion_fiscal']['localidad_id'] : null,
                    'municipio_id' => $data['direccion_fiscal']['municipio_id'] ? $data['direccion_fiscal']['municipio_id'] : null,
                    'estado_id' => $data['direccion_fiscal']['estado_id'] ? $data['direccion_fiscal']['estado_id'] : null,
                    'referencia' => $data['direccion_fiscal']['referencia'],
                ]);
                if (count($this->company->direccion_fiscal->getDirty()) > 0) {
                    $attributes = Arr::except($this->company->direccion_fiscal->getDirty(), ['created_at', 'updated_at']);
                    if ($this->company->rfc) {
                        $log = __('site.clients.save.address_updated_rfc', ['rfc' => $this->company->rfc]);
                    } else {
                        $log = __('site.clients.save.address_updated_commercial_name', ['nombre_comercial' => Crypt::decrypt($this->company->nombre_comercial)]);
                    }
                    activity(__('site.clients.save.fiscal_address_updated'))
                        ->on($this->company->direccion_fiscal)
                        ->event('updated')
                        ->withProperty('attributes', Direccion::parseData($attributes))
                        ->withProperty('old', Direccion::parseData(Arr::only($this->company->direccion_fiscal->getOriginal(), array_keys($attributes))))
                        ->log($log);
                    $this->company->direccion_fiscal->save();
                }
            } else {
                $dir = Direccion::create([
                    'calle' => $data['direccion_fiscal']['calle'],
                    'no_exterior' => $data['direccion_fiscal']['no_exterior'],
                    'no_interior' => $data['direccion_fiscal']['no_interior'],
                    'codigo_postal' => $data['direccion_fiscal']['codigo_postal'],
                    'colonia' => $data['direccion_fiscal']['colonia'],
                    'localidad_id' => $data['direccion_fiscal']['localidad_id'] ? $data['direccion_fiscal']['localidad_id'] : null,
                    'municipio_id' => $data['direccion_fiscal']['municipio_id'] ? $data['direccion_fiscal']['municipio_id'] : null,
                    'estado_id' => $data['direccion_fiscal']['estado_id'] ? $data['direccion_fiscal']['estado_id'] : null,
                    'referencia' => $data['direccion_fiscal']['referencia'],
                ]);
                $this->company->direccion_fiscal_id = $dir->id;
                $this->company->save();

                if ($this->company->rfc) {
                    $log = __('site.clients.save.address_created_rfc', ['rfc' => $this->company->rfc]);
                } else {
                    $log = __('site.clients.save.address_created_commercial_name', ['nombre_comercial' => Crypt::decrypt($this->company->nombre_comercial)]);
                }

                activity(__('site.clients.save.fiscal_address_created'))
                    ->on($dir)
                    ->event('created')
                    ->withProperties(Direccion::parseData(Arr::except($dir->toArray(), ['updated_at'])))
                    ->log($log);
            }

            if ($this->logo && !is_string($this->logo)) {
                $ext = $this->logo->extension();
                $nombre = Str::uuid() . ".$ext";
                $this->logo->storeAs('', $nombre, 'logos');
                $this->company->logo = $nombre;
            } else if (!$this->logo && !$this->logo_src) {
                if ($this->company->logo && Storage::disk('logos')->exists($this->company->logo)) {
                    Storage::disk('logos')->delete($this->company->logo);
                }
                $this->company->logo = null;
            }
            $this->company->save();

            $this->dispatch('show-toast', __('site.clients.save.client_saved_successfully'));
            $this->dispatch('$refresh');
            DB::commit();
            $this->dispatch('closeModal');
        } catch (\Exception $e) {
            DB::rollBack();
            Log::error($e->getMessage());
            $this->dispatch('show-toast', __('site.clients.save.client_save_failed'), 'danger');
        }
    }

    public function init()
    {
        if (user()->cannot('myCompany-view')) {
            $this->dispatch('show-toast', __('site.common.client_no_permissions'), 'danger');
            $this->dispatch('closeModal');
            return;
        }

        if ($this->direccion_fiscal['estado_id']) {
            $estado = Estado::find($this->direccion_fiscal['estado_id']);
            $this->dispatch("set-data-direccion_fiscal-estado_id", ['data' => [$estado->only('id', 'text')], 'term' => '', 'value' => $estado->id]);
        }
        if ($this->direccion_fiscal['localidad_id']) {
            $localidad = Localidad::find($this->direccion_fiscal['localidad_id']);
            $this->dispatch("set-data-direccion_fiscal-localidad_id", ['data' => [$localidad->only('id', 'text')], 'term' => '', 'value' => $localidad->id]);
        }
        if ($this->direccion_fiscal['municipio_id']) {
            $municipio = Municipio::find($this->direccion_fiscal['municipio_id']);
            $this->dispatch("set-data-direccion_fiscal-municipio_id", ['data' => [$municipio->only('id', 'text')], 'term' => '', 'value' => $municipio->id]);
        }
    }

    public function removeLogo()
    {
        $this->logo = null;
        $this->logo_src = '';
    }
}
