<?php

namespace App\Http\Livewire\Layouts;

use LivewireUI\Modal\ModalComponent;

class Modal extends ModalComponent
{

    public static function modalMaxWidthClass(): string
    {
        return 'modal-lg'; // TODO: Change the autogenerated stub
    }

}
